package com.parsd.patientengine.pojo;
// Generated Apr 20, 2016 9:22:47 PM by Hibernate Tools 4.3.1



/**
 * Address generated by hbm2java
 */
public class Address  implements java.io.Serializable {


     private String addressId;
     private String street;
     private String city;
     private String state;
     private String zipcode;
     private String country;
     private String patientUpi;

    public Address() {
    }

	
    public Address(String addressId, String street, String city, String state, String zipcode, String country) {
        this.addressId = addressId;
        this.street = street;
        this.city = city;
        this.state = state;
        this.zipcode = zipcode;
        this.country = country;
    }
    public Address(String addressId, String street, String city, String state, String zipcode, String country, String patientUpi) {
       this.addressId = addressId;
       this.street = street;
       this.city = city;
       this.state = state;
       this.zipcode = zipcode;
       this.country = country;
       this.patientUpi = patientUpi;
    }
   
    public String getAddressId() {
        return this.addressId;
    }
    
    public void setAddressId(String addressId) {
        this.addressId = addressId;
    }
    public String getStreet() {
        return this.street;
    }
    
    public void setStreet(String street) {
        this.street = street;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public String getZipcode() {
        return this.zipcode;
    }
    
    public void setZipcode(String zipcode) {
        this.zipcode = zipcode;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getPatientUpi() {
        return this.patientUpi;
    }
    
    public void setPatientUpi(String patientUpi) {
        this.patientUpi = patientUpi;
    }




}


