package com.parsd.patientengine.pojo;
// Generated Apr 20, 2016 9:22:47 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * DisabilityLk generated by hbm2java
 */
public class DisabilityLk  implements java.io.Serializable {


     private int disabilityId;
     private String disabilityName;
     private String disabilityType;
     private Set<PatientDisability> patientDisabilities = new HashSet<PatientDisability>(0);

    public DisabilityLk() {
    }

	
    public DisabilityLk(int disabilityId, String disabilityName, String disabilityType) {
        this.disabilityId = disabilityId;
        this.disabilityName = disabilityName;
        this.disabilityType = disabilityType;
    }
    public DisabilityLk(int disabilityId, String disabilityName, String disabilityType, Set<PatientDisability> patientDisabilities) {
       this.disabilityId = disabilityId;
       this.disabilityName = disabilityName;
       this.disabilityType = disabilityType;
       this.patientDisabilities = patientDisabilities;
    }
   
    public int getDisabilityId() {
        return this.disabilityId;
    }
    
    public void setDisabilityId(int disabilityId) {
        this.disabilityId = disabilityId;
    }
    public String getDisabilityName() {
        return this.disabilityName;
    }
    
    public void setDisabilityName(String disabilityName) {
        this.disabilityName = disabilityName;
    }
    public String getDisabilityType() {
        return this.disabilityType;
    }
    
    public void setDisabilityType(String disabilityType) {
        this.disabilityType = disabilityType;
    }
    public Set<PatientDisability> getPatientDisabilities() {
        return this.patientDisabilities;
    }
    
    public void setPatientDisabilities(Set<PatientDisability> patientDisabilities) {
        this.patientDisabilities = patientDisabilities;
    }




}


