package com.parsd.patientengine.pojo;
// Generated Apr 20, 2016 9:22:47 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * DiseaseLk generated by hbm2java
 */
public class DiseaseLk  implements java.io.Serializable {


     private String diseaseIcd10;
     private String diseaseDesc;
     private Set<PatientDiseaseSummary> patientDiseaseSummaries = new HashSet<PatientDiseaseSummary>(0);

    public DiseaseLk() {
    }

	
    public DiseaseLk(String diseaseIcd10, String diseaseDesc) {
        this.diseaseIcd10 = diseaseIcd10;
        this.diseaseDesc = diseaseDesc;
    }
    public DiseaseLk(String diseaseIcd10, String diseaseDesc, Set<PatientDiseaseSummary> patientDiseaseSummaries) {
       this.diseaseIcd10 = diseaseIcd10;
       this.diseaseDesc = diseaseDesc;
       this.patientDiseaseSummaries = patientDiseaseSummaries;
    }
   
    public String getDiseaseIcd10() {
        return this.diseaseIcd10;
    }
    
    public void setDiseaseIcd10(String diseaseIcd10) {
        this.diseaseIcd10 = diseaseIcd10;
    }
    public String getDiseaseDesc() {
        return this.diseaseDesc;
    }
    
    public void setDiseaseDesc(String diseaseDesc) {
        this.diseaseDesc = diseaseDesc;
    }
    public Set<PatientDiseaseSummary> getPatientDiseaseSummaries() {
        return this.patientDiseaseSummaries;
    }
    
    public void setPatientDiseaseSummaries(Set<PatientDiseaseSummary> patientDiseaseSummaries) {
        this.patientDiseaseSummaries = patientDiseaseSummaries;
    }




}


