package com.parsd.patientengine.pojo;
// Generated Apr 20, 2016 9:22:47 PM by Hibernate Tools 4.3.1



/**
 * EmergencyContact generated by hbm2java
 */
public class EmergencyContact  implements java.io.Serializable {


     private String patientUpi;
     private Patient patient;
     private String primaryContactName;
     private String primaryPatientRelationship;
     private String primaryPhoneNumber;
     private String secondaryContactName;
     private String secondaryPatientRelationship;
     private String secondaryPhoneNumber;

    public EmergencyContact() {
    }

	
    public EmergencyContact(Patient patient, String primaryContactName, String primaryPatientRelationship, String primaryPhoneNumber) {
        this.patient = patient;
        this.primaryContactName = primaryContactName;
        this.primaryPatientRelationship = primaryPatientRelationship;
        this.primaryPhoneNumber = primaryPhoneNumber;
    }
    public EmergencyContact(Patient patient, String primaryContactName, String primaryPatientRelationship, String primaryPhoneNumber, String secondaryContactName, String secondaryPatientRelationship, String secondaryPhoneNumber) {
       this.patient = patient;
       this.primaryContactName = primaryContactName;
       this.primaryPatientRelationship = primaryPatientRelationship;
       this.primaryPhoneNumber = primaryPhoneNumber;
       this.secondaryContactName = secondaryContactName;
       this.secondaryPatientRelationship = secondaryPatientRelationship;
       this.secondaryPhoneNumber = secondaryPhoneNumber;
    }
   
    public String getPatientUpi() {
        return this.patientUpi;
    }
    
    public void setPatientUpi(String patientUpi) {
        this.patientUpi = patientUpi;
    }
    public Patient getPatient() {
        return this.patient;
    }
    
    public void setPatient(Patient patient) {
        this.patient = patient;
    }
    public String getPrimaryContactName() {
        return this.primaryContactName;
    }
    
    public void setPrimaryContactName(String primaryContactName) {
        this.primaryContactName = primaryContactName;
    }
    public String getPrimaryPatientRelationship() {
        return this.primaryPatientRelationship;
    }
    
    public void setPrimaryPatientRelationship(String primaryPatientRelationship) {
        this.primaryPatientRelationship = primaryPatientRelationship;
    }
    public String getPrimaryPhoneNumber() {
        return this.primaryPhoneNumber;
    }
    
    public void setPrimaryPhoneNumber(String primaryPhoneNumber) {
        this.primaryPhoneNumber = primaryPhoneNumber;
    }
    public String getSecondaryContactName() {
        return this.secondaryContactName;
    }
    
    public void setSecondaryContactName(String secondaryContactName) {
        this.secondaryContactName = secondaryContactName;
    }
    public String getSecondaryPatientRelationship() {
        return this.secondaryPatientRelationship;
    }
    
    public void setSecondaryPatientRelationship(String secondaryPatientRelationship) {
        this.secondaryPatientRelationship = secondaryPatientRelationship;
    }
    public String getSecondaryPhoneNumber() {
        return this.secondaryPhoneNumber;
    }
    
    public void setSecondaryPhoneNumber(String secondaryPhoneNumber) {
        this.secondaryPhoneNumber = secondaryPhoneNumber;
    }




}


