package com.parsd.patientengine.pojo;
// Generated Apr 20, 2016 9:22:47 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * HealthCareProxy generated by hbm2java
 */
public class HealthCareProxy  implements java.io.Serializable {


     private String patientUpi;
     private Patient patient;
     private String primaryAgentName;
     private String primaryPhoneNumber;
     private String primaryPrivileges;
     private Date primaryStartDate;
     private Date primaryEndDate;
     private String secondaryAgentName;
     private String secondaryPhoneNumber;
     private String secondaryPrivileges;
     private Date secondaryStartDate;
     private Date secondaryEndDate;

    public HealthCareProxy() {
    }

	
    public HealthCareProxy(Patient patient, String primaryAgentName, String primaryPhoneNumber, String primaryPrivileges) {
        this.patient = patient;
        this.primaryAgentName = primaryAgentName;
        this.primaryPhoneNumber = primaryPhoneNumber;
        this.primaryPrivileges = primaryPrivileges;
    }
    public HealthCareProxy(Patient patient, String primaryAgentName, String primaryPhoneNumber, String primaryPrivileges, Date primaryStartDate, Date primaryEndDate, String secondaryAgentName, String secondaryPhoneNumber, String secondaryPrivileges, Date secondaryStartDate, Date secondaryEndDate) {
       this.patient = patient;
       this.primaryAgentName = primaryAgentName;
       this.primaryPhoneNumber = primaryPhoneNumber;
       this.primaryPrivileges = primaryPrivileges;
       this.primaryStartDate = primaryStartDate;
       this.primaryEndDate = primaryEndDate;
       this.secondaryAgentName = secondaryAgentName;
       this.secondaryPhoneNumber = secondaryPhoneNumber;
       this.secondaryPrivileges = secondaryPrivileges;
       this.secondaryStartDate = secondaryStartDate;
       this.secondaryEndDate = secondaryEndDate;
    }
   
    public String getPatientUpi() {
        return this.patientUpi;
    }
    
    public void setPatientUpi(String patientUpi) {
        this.patientUpi = patientUpi;
    }
    public Patient getPatient() {
        return this.patient;
    }
    
    public void setPatient(Patient patient) {
        this.patient = patient;
    }
    public String getPrimaryAgentName() {
        return this.primaryAgentName;
    }
    
    public void setPrimaryAgentName(String primaryAgentName) {
        this.primaryAgentName = primaryAgentName;
    }
    public String getPrimaryPhoneNumber() {
        return this.primaryPhoneNumber;
    }
    
    public void setPrimaryPhoneNumber(String primaryPhoneNumber) {
        this.primaryPhoneNumber = primaryPhoneNumber;
    }
    public String getPrimaryPrivileges() {
        return this.primaryPrivileges;
    }
    
    public void setPrimaryPrivileges(String primaryPrivileges) {
        this.primaryPrivileges = primaryPrivileges;
    }
    public Date getPrimaryStartDate() {
        return this.primaryStartDate;
    }
    
    public void setPrimaryStartDate(Date primaryStartDate) {
        this.primaryStartDate = primaryStartDate;
    }
    public Date getPrimaryEndDate() {
        return this.primaryEndDate;
    }
    
    public void setPrimaryEndDate(Date primaryEndDate) {
        this.primaryEndDate = primaryEndDate;
    }
    public String getSecondaryAgentName() {
        return this.secondaryAgentName;
    }
    
    public void setSecondaryAgentName(String secondaryAgentName) {
        this.secondaryAgentName = secondaryAgentName;
    }
    public String getSecondaryPhoneNumber() {
        return this.secondaryPhoneNumber;
    }
    
    public void setSecondaryPhoneNumber(String secondaryPhoneNumber) {
        this.secondaryPhoneNumber = secondaryPhoneNumber;
    }
    public String getSecondaryPrivileges() {
        return this.secondaryPrivileges;
    }
    
    public void setSecondaryPrivileges(String secondaryPrivileges) {
        this.secondaryPrivileges = secondaryPrivileges;
    }
    public Date getSecondaryStartDate() {
        return this.secondaryStartDate;
    }
    
    public void setSecondaryStartDate(Date secondaryStartDate) {
        this.secondaryStartDate = secondaryStartDate;
    }
    public Date getSecondaryEndDate() {
        return this.secondaryEndDate;
    }
    
    public void setSecondaryEndDate(Date secondaryEndDate) {
        this.secondaryEndDate = secondaryEndDate;
    }




}


