package com.parsd.patientengine.pojo;
// Generated Apr 20, 2016 9:22:47 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * LabTestHistory generated by hbm2java
 */
public class LabTestHistory  implements java.io.Serializable {


     private LabTestHistoryId id;
     private LabTestLk labTestLk;
     private PatientEvent patientEvent;
     private Date timeReported;
     private Date timeCollected;
     private String result;
     private String status;

    public LabTestHistory() {
    }

    public LabTestHistory(LabTestHistoryId id, LabTestLk labTestLk, PatientEvent patientEvent, Date timeReported, Date timeCollected, String result, String status) {
       this.id = id;
       this.labTestLk = labTestLk;
       this.patientEvent = patientEvent;
       this.timeReported = timeReported;
       this.timeCollected = timeCollected;
       this.result = result;
       this.status = status;
    }
   
    public LabTestHistoryId getId() {
        return this.id;
    }
    
    public void setId(LabTestHistoryId id) {
        this.id = id;
    }
    public LabTestLk getLabTestLk() {
        return this.labTestLk;
    }
    
    public void setLabTestLk(LabTestLk labTestLk) {
        this.labTestLk = labTestLk;
    }
    public PatientEvent getPatientEvent() {
        return this.patientEvent;
    }
    
    public void setPatientEvent(PatientEvent patientEvent) {
        this.patientEvent = patientEvent;
    }
    public Date getTimeReported() {
        return this.timeReported;
    }
    
    public void setTimeReported(Date timeReported) {
        this.timeReported = timeReported;
    }
    public Date getTimeCollected() {
        return this.timeCollected;
    }
    
    public void setTimeCollected(Date timeCollected) {
        this.timeCollected = timeCollected;
    }
    public String getResult() {
        return this.result;
    }
    
    public void setResult(String result) {
        this.result = result;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


