package com.parsd.patientengine.pojo;
// Generated Apr 20, 2016 9:22:47 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * PatientEvent generated by hbm2java
 */
public class PatientEvent  implements java.io.Serializable {


     private PatientEventId id;
     private Doctor doctor;
     private Patient patient;
     private String eventDesc;
     private String patientType;
     private VitalSigns vitalSigns;
     private Treatment treatment;
     private Set<LabTestHistory> labTestHistories = new HashSet<LabTestHistory>(0);
     private Set<BedAssignment> bedAssignments = new HashSet<BedAssignment>(0);
     private Set<Prescription> prescriptions = new HashSet<Prescription>(0);

    public PatientEvent() {
    	patient = new Patient();
    	doctor = new Doctor();
    }

	
    public PatientEvent(PatientEventId id, Doctor doctor, Patient patient, String eventDesc, String patientType) {
        this.id = id;
        this.doctor = doctor;
        this.patient = patient;
        this.eventDesc = eventDesc;
        this.patientType = patientType;
    }
    public PatientEvent(PatientEventId id, Doctor doctor, Patient patient, String eventDesc, String patientType, VitalSigns vitalSigns, Treatment treatment, Set<LabTestHistory> labTestHistories, Set<BedAssignment> bedAssignments, Set<Prescription> prescriptions) {
       this.id = id;
       this.doctor = doctor;
       this.patient = patient;
       this.eventDesc = eventDesc;
       this.patientType = patientType;
       this.vitalSigns = vitalSigns;
       this.treatment = treatment;
       this.labTestHistories = labTestHistories;
       this.bedAssignments = bedAssignments;
       this.prescriptions = prescriptions;
    }
   
    public PatientEventId getId() {
        return this.id;
    }
    
    public void setId(PatientEventId id) {
        this.id = id;
    }
    public Doctor getDoctor() {
        return this.doctor;
    }
    
    public void setDoctor(Doctor doctor) {
        this.doctor = doctor;
    }
    public Patient getPatient() {
        return this.patient;
    }
    
    public void setPatient(Patient patient) {
        this.patient = patient;
    }
    public String getEventDesc() {
        return this.eventDesc;
    }
    
    public void setEventDesc(String eventDesc) {
        this.eventDesc = eventDesc;
    }
    public String getPatientType() {
        return this.patientType;
    }
    
    public void setPatientType(String patientType) {
        this.patientType = patientType;
    }
    public VitalSigns getVitalSigns() {
        return this.vitalSigns;
    }
    
    public void setVitalSigns(VitalSigns vitalSigns) {
        this.vitalSigns = vitalSigns;
    }
    public Treatment getTreatment() {
        return this.treatment;
    }
    
    public void setTreatment(Treatment treatment) {
        this.treatment = treatment;
    }
    public Set<LabTestHistory> getLabTestHistories() {
        return this.labTestHistories;
    }
    
    public void setLabTestHistories(Set<LabTestHistory> labTestHistories) {
        this.labTestHistories = labTestHistories;
    }
    public Set<BedAssignment> getBedAssignments() {
        return this.bedAssignments;
    }
    
    public void setBedAssignments(Set<BedAssignment> bedAssignments) {
        this.bedAssignments = bedAssignments;
    }
    public Set<Prescription> getPrescriptions() {
        return this.prescriptions;
    }
    
    public void setPrescriptions(Set<Prescription> prescriptions) {
        this.prescriptions = prescriptions;
    }




}


