package com.parsd.patientengine.pojo;
// Generated Apr 20, 2016 9:22:47 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * PatientSurgeryHistory generated by hbm2java
 */
public class PatientSurgeryHistory  implements java.io.Serializable {


     private PatientSurgeryHistoryId id;
     private Patient patient;
     private Date surgeryDate;
     private String surgeryPerformedby;
     private String surgeryType;
     private String surgeryDescription;

    public PatientSurgeryHistory() {
    }

	
    public PatientSurgeryHistory(PatientSurgeryHistoryId id, Patient patient, Date surgeryDate, String surgeryPerformedby) {
        this.id = id;
        this.patient = patient;
        this.surgeryDate = surgeryDate;
        this.surgeryPerformedby = surgeryPerformedby;
    }
    public PatientSurgeryHistory(PatientSurgeryHistoryId id, Patient patient, Date surgeryDate, String surgeryPerformedby, String surgeryType, String surgeryDescription) {
       this.id = id;
       this.patient = patient;
       this.surgeryDate = surgeryDate;
       this.surgeryPerformedby = surgeryPerformedby;
       this.surgeryType = surgeryType;
       this.surgeryDescription = surgeryDescription;
    }
   
    public PatientSurgeryHistoryId getId() {
        return this.id;
    }
    
    public void setId(PatientSurgeryHistoryId id) {
        this.id = id;
    }
    public Patient getPatient() {
        return this.patient;
    }
    
    public void setPatient(Patient patient) {
        this.patient = patient;
    }
    public Date getSurgeryDate() {
        return this.surgeryDate;
    }
    
    public void setSurgeryDate(Date surgeryDate) {
        this.surgeryDate = surgeryDate;
    }
    public String getSurgeryPerformedby() {
        return this.surgeryPerformedby;
    }
    
    public void setSurgeryPerformedby(String surgeryPerformedby) {
        this.surgeryPerformedby = surgeryPerformedby;
    }
    public String getSurgeryType() {
        return this.surgeryType;
    }
    
    public void setSurgeryType(String surgeryType) {
        this.surgeryType = surgeryType;
    }
    public String getSurgeryDescription() {
        return this.surgeryDescription;
    }
    
    public void setSurgeryDescription(String surgeryDescription) {
        this.surgeryDescription = surgeryDescription;
    }




}


