package com.parsd.patientengine.pojo;
// Generated Apr 20, 2016 9:22:47 PM by Hibernate Tools 4.3.1



/**
 * PatientImmunizationId generated by hbm2java
 */
public class PatientImmunizationId  implements java.io.Serializable {


     private String patientUpi;
     private int immunizationId;

    public PatientImmunizationId() {
    }

    public PatientImmunizationId(String patientUpi, int immunizationId) {
       this.patientUpi = patientUpi;
       this.immunizationId = immunizationId;
    }
   
    public String getPatientUpi() {
        return this.patientUpi;
    }
    
    public void setPatientUpi(String patientUpi) {
        this.patientUpi = patientUpi;
    }
    public int getImmunizationId() {
        return this.immunizationId;
    }
    
    public void setImmunizationId(int immunizationId) {
        this.immunizationId = immunizationId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PatientImmunizationId) ) return false;
		 PatientImmunizationId castOther = ( PatientImmunizationId ) other; 
         
		 return ( (this.getPatientUpi()==castOther.getPatientUpi()) || ( this.getPatientUpi()!=null && castOther.getPatientUpi()!=null && this.getPatientUpi().equals(castOther.getPatientUpi()) ) )
 && (this.getImmunizationId()==castOther.getImmunizationId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPatientUpi() == null ? 0 : this.getPatientUpi().hashCode() );
         result = 37 * result + this.getImmunizationId();
         return result;
   }   


}


