package com.parsd.patientengine.pojo;
// Generated Apr 20, 2016 9:22:47 PM by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Patient generated by hbm2java
 */
public class Patient  implements java.io.Serializable {


     private String patientUpi;
     private String patientFname;
     private String patientLname;
     private Date patientDob;
     private char gender;
     private char disabilityStatus;
     private String cellPhone;
     private String emergencyContactName;
     private String emergencyContactNumber;
     private String emergencyContactRelationship;
     private String patientMname;
     private String bloodGroup;
     private String homePhone;
     private String maritalStatus;
     private String patientPcpName;
     private Set<PatientImmunization> patientImmunizations = new HashSet<PatientImmunization>(0);
     private EmergencyContact emergencyContact;
     private Set<PatientSurgeryHistory> patientSurgeryHistories = new HashSet<PatientSurgeryHistory>(0);
     private Set<PatientEvent> patientEvents = new HashSet<PatientEvent>(0);
     private Set<PatientAllergy> patientAllergies = new HashSet<PatientAllergy>(0);
     private HealthCareProxy healthCareProxy;
     private SocialHabits socialHabits;
     private FamilyHistory familyHistory;
     private Set<PatientDiseaseSummary> patientDiseaseSummaries = new HashSet<PatientDiseaseSummary>(0);
     private Set<PatientInsuranceHistory> patientInsuranceHistories = new HashSet<PatientInsuranceHistory>(0);
     private Set<PatientDisability> patientDisabilities = new HashSet<PatientDisability>(0);
     private List<Address> addresses = new ArrayList<Address>(0);
    public Patient() {
    }

	
    public Patient(String patientUpi, String patientFname, String patientLname, Date patientDob, char gender, char disabilityStatus, String cellPhone, String emergencyContactName, String emergencyContactNumber, String emergencyContactRelationship) {
        this.patientUpi = patientUpi;
        this.patientFname = patientFname;
        this.patientLname = patientLname;
        this.patientDob = patientDob;
        this.gender = gender;
        this.disabilityStatus = disabilityStatus;
        this.cellPhone = cellPhone;
        this.emergencyContactName = emergencyContactName;
        this.emergencyContactNumber = emergencyContactNumber;
        this.emergencyContactRelationship = emergencyContactRelationship;
    }
    public Patient(String patientUpi, String patientFname, String patientLname, Date patientDob, char gender, char disabilityStatus, String cellPhone, String emergencyContactName, String emergencyContactNumber, String emergencyContactRelationship, String patientMname, String bloodGroup, String homePhone, String maritalStatus, String patientPcpName, Set<PatientImmunization> patientImmunizations, EmergencyContact emergencyContact, Set<PatientSurgeryHistory> patientSurgeryHistories, Set<PatientEvent> patientEvents, Set<PatientAllergy> patientAllergies, HealthCareProxy healthCareProxy, SocialHabits socialHabits, FamilyHistory familyHistory, Set<PatientDiseaseSummary> patientDiseaseSummaries, Set<PatientInsuranceHistory> patientInsuranceHistories, Set<PatientDisability> patientDisabilities) {
       this.patientUpi = patientUpi;
       this.patientFname = patientFname;
       this.patientLname = patientLname;
       this.patientDob = patientDob;
       this.gender = gender;
       this.disabilityStatus = disabilityStatus;
       this.cellPhone = cellPhone;
       this.emergencyContactName = emergencyContactName;
       this.emergencyContactNumber = emergencyContactNumber;
       this.emergencyContactRelationship = emergencyContactRelationship;
       this.patientMname = patientMname;
       this.bloodGroup = bloodGroup;
       this.homePhone = homePhone;
       this.maritalStatus = maritalStatus;
       this.patientPcpName = patientPcpName;
       this.patientImmunizations = patientImmunizations;
       this.emergencyContact = emergencyContact;
       this.patientSurgeryHistories = patientSurgeryHistories;
       this.patientEvents = patientEvents;
       this.patientAllergies = patientAllergies;
       this.healthCareProxy = healthCareProxy;
       this.socialHabits = socialHabits;
       this.familyHistory = familyHistory;
       this.patientDiseaseSummaries = patientDiseaseSummaries;
       this.patientInsuranceHistories = patientInsuranceHistories;
       this.patientDisabilities = patientDisabilities;
    }
   
    public String getPatientUpi() {
        return this.patientUpi;
    }
    
    public void setPatientUpi(String patientUpi) {
        this.patientUpi = patientUpi;
    }
    public String getPatientFname() {
        return this.patientFname;
    }
    
    public void setPatientFname(String patientFname) {
        this.patientFname = patientFname;
    }
    public String getPatientLname() {
        return this.patientLname;
    }
    
    public void setPatientLname(String patientLname) {
        this.patientLname = patientLname;
    }
    public Date getPatientDob() {
        return this.patientDob;
    }
    
    public void setPatientDob(Date patientDob) {
        this.patientDob = patientDob;
    }
    public char getGender() {
        return this.gender;
    }
    
    public void setGender(char gender) {
        this.gender = gender;
    }
    public char getDisabilityStatus() {
        return this.disabilityStatus;
    }
    
    public void setDisabilityStatus(char disabilityStatus) {
        this.disabilityStatus = disabilityStatus;
    }
    public String getCellPhone() {
        return this.cellPhone;
    }
    
    public void setCellPhone(String cellPhone) {
        this.cellPhone = cellPhone;
    }
    public String getEmergencyContactName() {
        return this.emergencyContactName;
    }
    
    public void setEmergencyContactName(String emergencyContactName) {
        this.emergencyContactName = emergencyContactName;
    }
    public String getEmergencyContactNumber() {
        return this.emergencyContactNumber;
    }
    
    public void setEmergencyContactNumber(String emergencyContactNumber) {
        this.emergencyContactNumber = emergencyContactNumber;
    }
    public String getEmergencyContactRelationship() {
        return this.emergencyContactRelationship;
    }
    
    public void setEmergencyContactRelationship(String emergencyContactRelationship) {
        this.emergencyContactRelationship = emergencyContactRelationship;
    }
    public String getPatientMname() {
        return this.patientMname;
    }
    
    public void setPatientMname(String patientMname) {
        this.patientMname = patientMname;
    }
    public String getBloodGroup() {
        return this.bloodGroup;
    }
    
    public void setBloodGroup(String bloodGroup) {
        this.bloodGroup = bloodGroup;
    }
    public String getHomePhone() {
        return this.homePhone;
    }
    
    public void setHomePhone(String homePhone) {
        this.homePhone = homePhone;
    }
    public String getMaritalStatus() {
        return this.maritalStatus;
    }
    
    public void setMaritalStatus(String maritalStatus) {
        this.maritalStatus = maritalStatus;
    }
    public String getPatientPcpName() {
        return this.patientPcpName;
    }
    
    public void setPatientPcpName(String patientPcpName) {
        this.patientPcpName = patientPcpName;
    }
    public Set<PatientImmunization> getPatientImmunizations() {
        return this.patientImmunizations;
    }
    
    public void setPatientImmunizations(Set<PatientImmunization> patientImmunizations) {
        this.patientImmunizations = patientImmunizations;
    }
    public EmergencyContact getEmergencyContact() {
        return this.emergencyContact;
    }
    
    public void setEmergencyContact(EmergencyContact emergencyContact) {
        this.emergencyContact = emergencyContact;
    }
    public Set<PatientSurgeryHistory> getPatientSurgeryHistories() {
        return this.patientSurgeryHistories;
    }
    
    public void setPatientSurgeryHistories(Set<PatientSurgeryHistory> patientSurgeryHistories) {
        this.patientSurgeryHistories = patientSurgeryHistories;
    }
    public Set<PatientEvent> getPatientEvents() {
        return this.patientEvents;
    }
    
    public void setPatientEvents(Set<PatientEvent> patientEvents) {
        this.patientEvents = patientEvents;
    }
    public Set<PatientAllergy> getPatientAllergies() {
        return this.patientAllergies;
    }
    
    public void setPatientAllergies(Set<PatientAllergy> patientAllergies) {
        this.patientAllergies = patientAllergies;
    }
    public HealthCareProxy getHealthCareProxy() {
        return this.healthCareProxy;
    }
    
    public void setHealthCareProxy(HealthCareProxy healthCareProxy) {
        this.healthCareProxy = healthCareProxy;
    }
    public SocialHabits getSocialHabits() {
        return this.socialHabits;
    }
    
    public void setSocialHabits(SocialHabits socialHabits) {
        this.socialHabits = socialHabits;
    }
    public FamilyHistory getFamilyHistory() {
        return this.familyHistory;
    }
    
    public void setFamilyHistory(FamilyHistory familyHistory) {
        this.familyHistory = familyHistory;
    }
    public Set<PatientDiseaseSummary> getPatientDiseaseSummaries() {
        return this.patientDiseaseSummaries;
    }
    
    public void setPatientDiseaseSummaries(Set<PatientDiseaseSummary> patientDiseaseSummaries) {
        this.patientDiseaseSummaries = patientDiseaseSummaries;
    }
    public Set<PatientInsuranceHistory> getPatientInsuranceHistories() {
        return this.patientInsuranceHistories;
    }
    
    public void setPatientInsuranceHistories(Set<PatientInsuranceHistory> patientInsuranceHistories) {
        this.patientInsuranceHistories = patientInsuranceHistories;
    }
    public Set<PatientDisability> getPatientDisabilities() {
        return this.patientDisabilities;
    }
    
    public void setPatientDisabilities(Set<PatientDisability> patientDisabilities) {
        this.patientDisabilities = patientDisabilities;
    }


	public List<Address> getAddresses() {
		return addresses;
	}


	public void setAddresses(List<Address> addresses) {
		this.addresses = addresses;
	}

}


