package com.parsd.patientengine.pojo;
// Generated Apr 20, 2016 9:22:47 PM by Hibernate Tools 4.3.1



/**
 * PatientDiseaseSummaryId generated by hbm2java
 */
public class PatientDiseaseSummaryId  implements java.io.Serializable {


     private String patientUpi;
     private String diseaseIcd10;

    public PatientDiseaseSummaryId() {
    }

    public PatientDiseaseSummaryId(String patientUpi, String diseaseIcd10) {
       this.patientUpi = patientUpi;
       this.diseaseIcd10 = diseaseIcd10;
    }
   
    public String getPatientUpi() {
        return this.patientUpi;
    }
    
    public void setPatientUpi(String patientUpi) {
        this.patientUpi = patientUpi;
    }
    public String getDiseaseIcd10() {
        return this.diseaseIcd10;
    }
    
    public void setDiseaseIcd10(String diseaseIcd10) {
        this.diseaseIcd10 = diseaseIcd10;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PatientDiseaseSummaryId) ) return false;
		 PatientDiseaseSummaryId castOther = ( PatientDiseaseSummaryId ) other; 
         
		 return ( (this.getPatientUpi()==castOther.getPatientUpi()) || ( this.getPatientUpi()!=null && castOther.getPatientUpi()!=null && this.getPatientUpi().equals(castOther.getPatientUpi()) ) )
 && ( (this.getDiseaseIcd10()==castOther.getDiseaseIcd10()) || ( this.getDiseaseIcd10()!=null && castOther.getDiseaseIcd10()!=null && this.getDiseaseIcd10().equals(castOther.getDiseaseIcd10()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPatientUpi() == null ? 0 : this.getPatientUpi().hashCode() );
         result = 37 * result + ( getDiseaseIcd10() == null ? 0 : this.getDiseaseIcd10().hashCode() );
         return result;
   }   


}


