package com.parsd.patientengine.pojo;
// Generated Apr 20, 2016 9:22:47 PM by Hibernate Tools 4.3.1



/**
 * SocialHabits generated by hbm2java
 */
public class SocialHabits  implements java.io.Serializable {


     private String patientUpi;
     private Patient patient;
     private Character smokingHabit;
     private Integer smokingYears;
     private Character alcoholHabit;
     private Integer alcoholYears;
     private Character recreationalDrugs;

    public SocialHabits() {
    }

	
    public SocialHabits(Patient patient) {
        this.patient = patient;
    }
    public SocialHabits(Patient patient, Character smokingHabit, Integer smokingYears, Character alcoholHabit, Integer alcoholYears, Character recreationalDrugs) {
       this.patient = patient;
       this.smokingHabit = smokingHabit;
       this.smokingYears = smokingYears;
       this.alcoholHabit = alcoholHabit;
       this.alcoholYears = alcoholYears;
       this.recreationalDrugs = recreationalDrugs;
    }
   
    public String getPatientUpi() {
        return this.patientUpi;
    }
    
    public void setPatientUpi(String patientUpi) {
        this.patientUpi = patientUpi;
    }
    public Patient getPatient() {
        return this.patient;
    }
    
    public void setPatient(Patient patient) {
        this.patient = patient;
    }
    public Character getSmokingHabit() {
        return this.smokingHabit;
    }
    
    public void setSmokingHabit(Character smokingHabit) {
        this.smokingHabit = smokingHabit;
    }
    public Integer getSmokingYears() {
        return this.smokingYears;
    }
    
    public void setSmokingYears(Integer smokingYears) {
        this.smokingYears = smokingYears;
    }
    public Character getAlcoholHabit() {
        return this.alcoholHabit;
    }
    
    public void setAlcoholHabit(Character alcoholHabit) {
        this.alcoholHabit = alcoholHabit;
    }
    public Integer getAlcoholYears() {
        return this.alcoholYears;
    }
    
    public void setAlcoholYears(Integer alcoholYears) {
        this.alcoholYears = alcoholYears;
    }
    public Character getRecreationalDrugs() {
        return this.recreationalDrugs;
    }
    
    public void setRecreationalDrugs(Character recreationalDrugs) {
        this.recreationalDrugs = recreationalDrugs;
    }




}


