package com.parsd.patientengine.pojo;
// Generated Apr 19, 2016 7:35:31 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AllergyLk generated by hbm2java
 */
@Entity
@Table(name="allergy_lk"
    ,catalog="patient"
)
public class AllergyLk  implements java.io.Serializable {


     private int allergyId;
     private String allergyName;
     private String allergyType;
     private Set<PatientAllergy> patientAllergies = new HashSet<PatientAllergy>(0);

    public AllergyLk() {
    }

	
    public AllergyLk(int allergyId, String allergyName, String allergyType) {
        this.allergyId = allergyId;
        this.allergyName = allergyName;
        this.allergyType = allergyType;
    }
    public AllergyLk(int allergyId, String allergyName, String allergyType, Set<PatientAllergy> patientAllergies) {
       this.allergyId = allergyId;
       this.allergyName = allergyName;
       this.allergyType = allergyType;
       this.patientAllergies = patientAllergies;
    }
   
     @Id 

    
    @Column(name="allergy_id", unique=true, nullable=false)
    public int getAllergyId() {
        return this.allergyId;
    }
    
    public void setAllergyId(int allergyId) {
        this.allergyId = allergyId;
    }

    
    @Column(name="allergy_name", nullable=false, length=30)
    public String getAllergyName() {
        return this.allergyName;
    }
    
    public void setAllergyName(String allergyName) {
        this.allergyName = allergyName;
    }

    
    @Column(name="allergy_type", nullable=false, length=20)
    public String getAllergyType() {
        return this.allergyType;
    }
    
    public void setAllergyType(String allergyType) {
        this.allergyType = allergyType;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="allergyLk")
    public Set<PatientAllergy> getPatientAllergies() {
        return this.patientAllergies;
    }
    
    public void setPatientAllergies(Set<PatientAllergy> patientAllergies) {
        this.patientAllergies = patientAllergies;
    }




}


