package com.parsd.patientengine.pojo;
// Generated Apr 19, 2016 7:35:31 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BedAssignment generated by hbm2java
 */
@Entity
@Table(name="bed_assignment"
    ,catalog="patient"
)
public class BedAssignment  implements java.io.Serializable {


     private int bedAssignmentId;
     private PatientEvent patientEvent;
     private Date dateFrom;
     private Date dateTill;
     private String wardType;

    public BedAssignment() {
    }

    public BedAssignment(int bedAssignmentId, PatientEvent patientEvent, Date dateFrom, Date dateTill, String wardType) {
       this.bedAssignmentId = bedAssignmentId;
       this.patientEvent = patientEvent;
       this.dateFrom = dateFrom;
       this.dateTill = dateTill;
       this.wardType = wardType;
    }
   
     @Id 

    
    @Column(name="bed_assignment_id", unique=true, nullable=false)
    public int getBedAssignmentId() {
        return this.bedAssignmentId;
    }
    
    public void setBedAssignmentId(int bedAssignmentId) {
        this.bedAssignmentId = bedAssignmentId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="patient_UPI", referencedColumnName="patient_UPI", nullable=false), 
        @JoinColumn(name="doctor_id", referencedColumnName="doctor_id", nullable=false), 
        @JoinColumn(name="event_date", referencedColumnName="event_date", nullable=false) } )
    public PatientEvent getPatientEvent() {
        return this.patientEvent;
    }
    
    public void setPatientEvent(PatientEvent patientEvent) {
        this.patientEvent = patientEvent;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_from", nullable=false, length=10)
    public Date getDateFrom() {
        return this.dateFrom;
    }
    
    public void setDateFrom(Date dateFrom) {
        this.dateFrom = dateFrom;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_till", nullable=false, length=10)
    public Date getDateTill() {
        return this.dateTill;
    }
    
    public void setDateTill(Date dateTill) {
        this.dateTill = dateTill;
    }

    
    @Column(name="ward_type", nullable=false, length=20)
    public String getWardType() {
        return this.wardType;
    }
    
    public void setWardType(String wardType) {
        this.wardType = wardType;
    }




}


