package com.parsd.patientengine.pojo;
// Generated Apr 19, 2016 7:35:31 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DisabilityLk generated by hbm2java
 */
@Entity
@Table(name="disability_lk"
    ,catalog="patient"
)
public class DisabilityLk  implements java.io.Serializable {


     private int disabilityId;
     private String disabilityName;
     private String disabilityType;
     private Set<PatientDisability> patientDisabilities = new HashSet<PatientDisability>(0);

    public DisabilityLk() {
    }

	
    public DisabilityLk(int disabilityId, String disabilityName, String disabilityType) {
        this.disabilityId = disabilityId;
        this.disabilityName = disabilityName;
        this.disabilityType = disabilityType;
    }
    public DisabilityLk(int disabilityId, String disabilityName, String disabilityType, Set<PatientDisability> patientDisabilities) {
       this.disabilityId = disabilityId;
       this.disabilityName = disabilityName;
       this.disabilityType = disabilityType;
       this.patientDisabilities = patientDisabilities;
    }
   
     @Id 

    
    @Column(name="disability_id", unique=true, nullable=false)
    public int getDisabilityId() {
        return this.disabilityId;
    }
    
    public void setDisabilityId(int disabilityId) {
        this.disabilityId = disabilityId;
    }

    
    @Column(name="disability_name", nullable=false, length=30)
    public String getDisabilityName() {
        return this.disabilityName;
    }
    
    public void setDisabilityName(String disabilityName) {
        this.disabilityName = disabilityName;
    }

    
    @Column(name="disability_type", nullable=false, length=20)
    public String getDisabilityType() {
        return this.disabilityType;
    }
    
    public void setDisabilityType(String disabilityType) {
        this.disabilityType = disabilityType;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="disabilityLk")
    public Set<PatientDisability> getPatientDisabilities() {
        return this.patientDisabilities;
    }
    
    public void setPatientDisabilities(Set<PatientDisability> patientDisabilities) {
        this.patientDisabilities = patientDisabilities;
    }




}


