package com.parsd.patientengine.pojo;
// Generated Apr 19, 2016 7:35:31 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DiseaseLk generated by hbm2java
 */
@Entity
@Table(name="disease_lk"
    ,catalog="patient"
)
public class DiseaseLk  implements java.io.Serializable {


     private String diseaseIcd10;
     private String diseaseDesc;
     private Set<PatientDiseaseSummary> patientDiseaseSummaries = new HashSet<PatientDiseaseSummary>(0);

    public DiseaseLk() {
    }

	
    public DiseaseLk(String diseaseIcd10, String diseaseDesc) {
        this.diseaseIcd10 = diseaseIcd10;
        this.diseaseDesc = diseaseDesc;
    }
    public DiseaseLk(String diseaseIcd10, String diseaseDesc, Set<PatientDiseaseSummary> patientDiseaseSummaries) {
       this.diseaseIcd10 = diseaseIcd10;
       this.diseaseDesc = diseaseDesc;
       this.patientDiseaseSummaries = patientDiseaseSummaries;
    }
   
     @Id 

    
    @Column(name="disease_ICD_10", unique=true, nullable=false, length=7)
    public String getDiseaseIcd10() {
        return this.diseaseIcd10;
    }
    
    public void setDiseaseIcd10(String diseaseIcd10) {
        this.diseaseIcd10 = diseaseIcd10;
    }

    
    @Column(name="disease_desc", nullable=false)
    public String getDiseaseDesc() {
        return this.diseaseDesc;
    }
    
    public void setDiseaseDesc(String diseaseDesc) {
        this.diseaseDesc = diseaseDesc;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="diseaseLk")
    public Set<PatientDiseaseSummary> getPatientDiseaseSummaries() {
        return this.patientDiseaseSummaries;
    }
    
    public void setPatientDiseaseSummaries(Set<PatientDiseaseSummary> patientDiseaseSummaries) {
        this.patientDiseaseSummaries = patientDiseaseSummaries;
    }




}


