package com.parsd.patientengine.pojo;
// Generated Apr 20, 2016 9:22:47 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Doctor generated by hbm2java
 */
public class Doctor  implements java.io.Serializable {


     private int doctorId;
     private String doctorUpin;
     private String doctorFname;
     private String doctorLname;
     private String doctorMname;
     private String doctorSpecialization;
     private Set<PatientEvent> patientEvents = new HashSet<PatientEvent>(0);

    public Doctor() {
    }

	
    public Doctor(int doctorId, String doctorUpin, String doctorFname, String doctorLname, String doctorSpecialization) {
        this.doctorId = doctorId;
        this.doctorUpin = doctorUpin;
        this.doctorFname = doctorFname;
        this.doctorLname = doctorLname;
        this.doctorSpecialization = doctorSpecialization;
    }
    public Doctor(int doctorId, String doctorUpin, String doctorFname, String doctorLname, String doctorMname, String doctorSpecialization, Set<PatientEvent> patientEvents) {
       this.doctorId = doctorId;
       this.doctorUpin = doctorUpin;
       this.doctorFname = doctorFname;
       this.doctorLname = doctorLname;
       this.doctorMname = doctorMname;
       this.doctorSpecialization = doctorSpecialization;
       this.patientEvents = patientEvents;
    }
   
    public int getDoctorId() {
        return this.doctorId;
    }
    
    public void setDoctorId(int doctorId) {
        this.doctorId = doctorId;
    }
    public String getDoctorUpin() {
        return this.doctorUpin;
    }
    
    public void setDoctorUpin(String doctorUpin) {
        this.doctorUpin = doctorUpin;
    }
    public String getDoctorFname() {
        return this.doctorFname;
    }
    
    public void setDoctorFname(String doctorFname) {
        this.doctorFname = doctorFname;
    }
    public String getDoctorLname() {
        return this.doctorLname;
    }
    
    public void setDoctorLname(String doctorLname) {
        this.doctorLname = doctorLname;
    }
    public String getDoctorMname() {
        return this.doctorMname;
    }
    
    public void setDoctorMname(String doctorMname) {
        this.doctorMname = doctorMname;
    }
    public String getDoctorSpecialization() {
        return this.doctorSpecialization;
    }
    
    public void setDoctorSpecialization(String doctorSpecialization) {
        this.doctorSpecialization = doctorSpecialization;
    }
    public Set<PatientEvent> getPatientEvents() {
        return this.patientEvents;
    }
    
    public void setPatientEvents(Set<PatientEvent> patientEvents) {
        this.patientEvents = patientEvents;
    }




}


