package com.parsd.patientengine.pojo;
// Generated Apr 19, 2016 7:35:31 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Doctor generated by hbm2java
 */
@Entity
@Table(name="doctor"
    ,catalog="patient"
)
public class Doctor  implements java.io.Serializable {


     private int doctorId;
     private String doctorUpin;
     private String doctorFname;
     private String doctorLname;
     private String doctorMname;
     private String doctorSpecialization;
     private Set<PatientEvent> patientEvents = new HashSet<PatientEvent>(0);

    public Doctor() {
    }

	
    public Doctor(int doctorId, String doctorUpin, String doctorFname, String doctorLname, String doctorSpecialization) {
        this.doctorId = doctorId;
        this.doctorUpin = doctorUpin;
        this.doctorFname = doctorFname;
        this.doctorLname = doctorLname;
        this.doctorSpecialization = doctorSpecialization;
    }
    public Doctor(int doctorId, String doctorUpin, String doctorFname, String doctorLname, String doctorMname, String doctorSpecialization, Set<PatientEvent> patientEvents) {
       this.doctorId = doctorId;
       this.doctorUpin = doctorUpin;
       this.doctorFname = doctorFname;
       this.doctorLname = doctorLname;
       this.doctorMname = doctorMname;
       this.doctorSpecialization = doctorSpecialization;
       this.patientEvents = patientEvents;
    }
   
     @Id 

    
    @Column(name="doctor_id", unique=true, nullable=false)
    public int getDoctorId() {
        return this.doctorId;
    }
    
    public void setDoctorId(int doctorId) {
        this.doctorId = doctorId;
    }

    
    @Column(name="doctor_UPIN", nullable=false, length=6)
    public String getDoctorUpin() {
        return this.doctorUpin;
    }
    
    public void setDoctorUpin(String doctorUpin) {
        this.doctorUpin = doctorUpin;
    }

    
    @Column(name="doctor_fname", nullable=false, length=20)
    public String getDoctorFname() {
        return this.doctorFname;
    }
    
    public void setDoctorFname(String doctorFname) {
        this.doctorFname = doctorFname;
    }

    
    @Column(name="doctor_lname", nullable=false, length=20)
    public String getDoctorLname() {
        return this.doctorLname;
    }
    
    public void setDoctorLname(String doctorLname) {
        this.doctorLname = doctorLname;
    }

    
    @Column(name="doctor_mname", length=20)
    public String getDoctorMname() {
        return this.doctorMname;
    }
    
    public void setDoctorMname(String doctorMname) {
        this.doctorMname = doctorMname;
    }

    
    @Column(name="doctor_specialization", nullable=false, length=20)
    public String getDoctorSpecialization() {
        return this.doctorSpecialization;
    }
    
    public void setDoctorSpecialization(String doctorSpecialization) {
        this.doctorSpecialization = doctorSpecialization;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="doctor")
    public Set<PatientEvent> getPatientEvents() {
        return this.patientEvents;
    }
    
    public void setPatientEvents(Set<PatientEvent> patientEvents) {
        this.patientEvents = patientEvents;
    }




}


