package com.parsd.patientengine.pojo;
// Generated Apr 19, 2016 7:35:31 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * EmergencyContact generated by hbm2java
 */
@Entity
@Table(name="emergency_contact"
    ,catalog="patient"
)
public class EmergencyContact  implements java.io.Serializable {


     private String patientUpi;
     private Patient patient;
     private String primaryContactName;
     private String primaryPatientRelationship;
     private String primaryPhoneNumber;
     private String secondaryContactName;
     private String secondaryPatientRelationship;
     private String secondaryPhoneNumber;

    public EmergencyContact() {
    }

	
    public EmergencyContact(Patient patient, String primaryContactName, String primaryPatientRelationship, String primaryPhoneNumber) {
        this.patient = patient;
        this.primaryContactName = primaryContactName;
        this.primaryPatientRelationship = primaryPatientRelationship;
        this.primaryPhoneNumber = primaryPhoneNumber;
    }
    public EmergencyContact(Patient patient, String primaryContactName, String primaryPatientRelationship, String primaryPhoneNumber, String secondaryContactName, String secondaryPatientRelationship, String secondaryPhoneNumber) {
       this.patient = patient;
       this.primaryContactName = primaryContactName;
       this.primaryPatientRelationship = primaryPatientRelationship;
       this.primaryPhoneNumber = primaryPhoneNumber;
       this.secondaryContactName = secondaryContactName;
       this.secondaryPatientRelationship = secondaryPatientRelationship;
       this.secondaryPhoneNumber = secondaryPhoneNumber;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="patient"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="patient_UPI", unique=true, nullable=false, length=6)
    public String getPatientUpi() {
        return this.patientUpi;
    }
    
    public void setPatientUpi(String patientUpi) {
        this.patientUpi = patientUpi;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Patient getPatient() {
        return this.patient;
    }
    
    public void setPatient(Patient patient) {
        this.patient = patient;
    }

    
    @Column(name="primary_contact_name", nullable=false, length=40)
    public String getPrimaryContactName() {
        return this.primaryContactName;
    }
    
    public void setPrimaryContactName(String primaryContactName) {
        this.primaryContactName = primaryContactName;
    }

    
    @Column(name="primary_patient_relationship", nullable=false, length=10)
    public String getPrimaryPatientRelationship() {
        return this.primaryPatientRelationship;
    }
    
    public void setPrimaryPatientRelationship(String primaryPatientRelationship) {
        this.primaryPatientRelationship = primaryPatientRelationship;
    }

    
    @Column(name="primary_phone_number", nullable=false, length=12)
    public String getPrimaryPhoneNumber() {
        return this.primaryPhoneNumber;
    }
    
    public void setPrimaryPhoneNumber(String primaryPhoneNumber) {
        this.primaryPhoneNumber = primaryPhoneNumber;
    }

    
    @Column(name="secondary_contact_name", length=40)
    public String getSecondaryContactName() {
        return this.secondaryContactName;
    }
    
    public void setSecondaryContactName(String secondaryContactName) {
        this.secondaryContactName = secondaryContactName;
    }

    
    @Column(name="secondary_patient_relationship", length=10)
    public String getSecondaryPatientRelationship() {
        return this.secondaryPatientRelationship;
    }
    
    public void setSecondaryPatientRelationship(String secondaryPatientRelationship) {
        this.secondaryPatientRelationship = secondaryPatientRelationship;
    }

    
    @Column(name="secondary_phone_number", length=12)
    public String getSecondaryPhoneNumber() {
        return this.secondaryPhoneNumber;
    }
    
    public void setSecondaryPhoneNumber(String secondaryPhoneNumber) {
        this.secondaryPhoneNumber = secondaryPhoneNumber;
    }




}


