package com.parsd.patientengine.pojo;
// Generated Apr 19, 2016 7:35:31 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * HealthCareProxy generated by hbm2java
 */
@Entity
@Table(name="health_care_proxy"
    ,catalog="patient"
)
public class HealthCareProxy  implements java.io.Serializable {


     private String patientUpi;
     private Patient patient;
     private String primaryAgentName;
     private String primaryPhoneNumber;
     private String primaryPrivileges;
     private Date primaryStartDate;
     private Date primaryEndDate;
     private String secondaryAgentName;
     private String secondaryPhoneNumber;
     private String secondaryPrivileges;
     private Date secondaryStartDate;
     private Date secondaryEndDate;

    public HealthCareProxy() {
    }

	
    public HealthCareProxy(Patient patient, String primaryAgentName, String primaryPhoneNumber, String primaryPrivileges) {
        this.patient = patient;
        this.primaryAgentName = primaryAgentName;
        this.primaryPhoneNumber = primaryPhoneNumber;
        this.primaryPrivileges = primaryPrivileges;
    }
    public HealthCareProxy(Patient patient, String primaryAgentName, String primaryPhoneNumber, String primaryPrivileges, Date primaryStartDate, Date primaryEndDate, String secondaryAgentName, String secondaryPhoneNumber, String secondaryPrivileges, Date secondaryStartDate, Date secondaryEndDate) {
       this.patient = patient;
       this.primaryAgentName = primaryAgentName;
       this.primaryPhoneNumber = primaryPhoneNumber;
       this.primaryPrivileges = primaryPrivileges;
       this.primaryStartDate = primaryStartDate;
       this.primaryEndDate = primaryEndDate;
       this.secondaryAgentName = secondaryAgentName;
       this.secondaryPhoneNumber = secondaryPhoneNumber;
       this.secondaryPrivileges = secondaryPrivileges;
       this.secondaryStartDate = secondaryStartDate;
       this.secondaryEndDate = secondaryEndDate;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="patient"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="patient_UPI", unique=true, nullable=false, length=6)
    public String getPatientUpi() {
        return this.patientUpi;
    }
    
    public void setPatientUpi(String patientUpi) {
        this.patientUpi = patientUpi;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Patient getPatient() {
        return this.patient;
    }
    
    public void setPatient(Patient patient) {
        this.patient = patient;
    }

    
    @Column(name="primary_agent_name", nullable=false, length=40)
    public String getPrimaryAgentName() {
        return this.primaryAgentName;
    }
    
    public void setPrimaryAgentName(String primaryAgentName) {
        this.primaryAgentName = primaryAgentName;
    }

    
    @Column(name="primary_phone_number", nullable=false, length=10)
    public String getPrimaryPhoneNumber() {
        return this.primaryPhoneNumber;
    }
    
    public void setPrimaryPhoneNumber(String primaryPhoneNumber) {
        this.primaryPhoneNumber = primaryPhoneNumber;
    }

    
    @Column(name="primary_privileges", nullable=false, length=20)
    public String getPrimaryPrivileges() {
        return this.primaryPrivileges;
    }
    
    public void setPrimaryPrivileges(String primaryPrivileges) {
        this.primaryPrivileges = primaryPrivileges;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="primary_start_date", length=10)
    public Date getPrimaryStartDate() {
        return this.primaryStartDate;
    }
    
    public void setPrimaryStartDate(Date primaryStartDate) {
        this.primaryStartDate = primaryStartDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="primary_end_date", length=10)
    public Date getPrimaryEndDate() {
        return this.primaryEndDate;
    }
    
    public void setPrimaryEndDate(Date primaryEndDate) {
        this.primaryEndDate = primaryEndDate;
    }

    
    @Column(name="secondary_agent_name", length=40)
    public String getSecondaryAgentName() {
        return this.secondaryAgentName;
    }
    
    public void setSecondaryAgentName(String secondaryAgentName) {
        this.secondaryAgentName = secondaryAgentName;
    }

    
    @Column(name="secondary_phone_number", length=10)
    public String getSecondaryPhoneNumber() {
        return this.secondaryPhoneNumber;
    }
    
    public void setSecondaryPhoneNumber(String secondaryPhoneNumber) {
        this.secondaryPhoneNumber = secondaryPhoneNumber;
    }

    
    @Column(name="secondary_privileges", length=20)
    public String getSecondaryPrivileges() {
        return this.secondaryPrivileges;
    }
    
    public void setSecondaryPrivileges(String secondaryPrivileges) {
        this.secondaryPrivileges = secondaryPrivileges;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="secondary_start_date", length=10)
    public Date getSecondaryStartDate() {
        return this.secondaryStartDate;
    }
    
    public void setSecondaryStartDate(Date secondaryStartDate) {
        this.secondaryStartDate = secondaryStartDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="secondary_end_date", length=10)
    public Date getSecondaryEndDate() {
        return this.secondaryEndDate;
    }
    
    public void setSecondaryEndDate(Date secondaryEndDate) {
        this.secondaryEndDate = secondaryEndDate;
    }




}


