package com.parsd.patientengine.pojo;
// Generated Apr 19, 2016 7:35:31 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ImmunizationDetailsLk generated by hbm2java
 */
@Entity
@Table(name="immunization_details_lk"
    ,catalog="patient"
)
public class ImmunizationDetailsLk  implements java.io.Serializable {


     private int immunizationId;
     private String immunizationName;
     private String immunizationType;
     private String suggestedAge;
     private String immunizationAgent;
     private Set<PatientImmunization> patientImmunizations = new HashSet<PatientImmunization>(0);

    public ImmunizationDetailsLk() {
    }

	
    public ImmunizationDetailsLk(int immunizationId, String immunizationName, String immunizationType, String suggestedAge, String immunizationAgent) {
        this.immunizationId = immunizationId;
        this.immunizationName = immunizationName;
        this.immunizationType = immunizationType;
        this.suggestedAge = suggestedAge;
        this.immunizationAgent = immunizationAgent;
    }
    public ImmunizationDetailsLk(int immunizationId, String immunizationName, String immunizationType, String suggestedAge, String immunizationAgent, Set<PatientImmunization> patientImmunizations) {
       this.immunizationId = immunizationId;
       this.immunizationName = immunizationName;
       this.immunizationType = immunizationType;
       this.suggestedAge = suggestedAge;
       this.immunizationAgent = immunizationAgent;
       this.patientImmunizations = patientImmunizations;
    }
   
     @Id 

    
    @Column(name="immunization_id", unique=true, nullable=false)
    public int getImmunizationId() {
        return this.immunizationId;
    }
    
    public void setImmunizationId(int immunizationId) {
        this.immunizationId = immunizationId;
    }

    
    @Column(name="immunization_name", nullable=false, length=30)
    public String getImmunizationName() {
        return this.immunizationName;
    }
    
    public void setImmunizationName(String immunizationName) {
        this.immunizationName = immunizationName;
    }

    
    @Column(name="immunization_type", nullable=false, length=20)
    public String getImmunizationType() {
        return this.immunizationType;
    }
    
    public void setImmunizationType(String immunizationType) {
        this.immunizationType = immunizationType;
    }

    
    @Column(name="suggested_age", nullable=false, length=10)
    public String getSuggestedAge() {
        return this.suggestedAge;
    }
    
    public void setSuggestedAge(String suggestedAge) {
        this.suggestedAge = suggestedAge;
    }

    
    @Column(name="immunization_agent", nullable=false, length=50)
    public String getImmunizationAgent() {
        return this.immunizationAgent;
    }
    
    public void setImmunizationAgent(String immunizationAgent) {
        this.immunizationAgent = immunizationAgent;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="immunizationDetailsLk")
    public Set<PatientImmunization> getPatientImmunizations() {
        return this.patientImmunizations;
    }
    
    public void setPatientImmunizations(Set<PatientImmunization> patientImmunizations) {
        this.patientImmunizations = patientImmunizations;
    }




}


