package com.parsd.patientengine.pojo;
// Generated Apr 20, 2016 9:22:47 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ImmunizationDetailsLk generated by hbm2java
 */
public class ImmunizationDetailsLk  implements java.io.Serializable {


     private int immunizationId;
     private String immunizationName;
     private String immunizationType;
     private String suggestedAge;
     private String immunizationAgent;
     private Set<PatientImmunization> patientImmunizations = new HashSet<PatientImmunization>(0);

    public ImmunizationDetailsLk() {
    }

	
    public ImmunizationDetailsLk(int immunizationId, String immunizationName, String immunizationType, String suggestedAge, String immunizationAgent) {
        this.immunizationId = immunizationId;
        this.immunizationName = immunizationName;
        this.immunizationType = immunizationType;
        this.suggestedAge = suggestedAge;
        this.immunizationAgent = immunizationAgent;
    }
    public ImmunizationDetailsLk(int immunizationId, String immunizationName, String immunizationType, String suggestedAge, String immunizationAgent, Set<PatientImmunization> patientImmunizations) {
       this.immunizationId = immunizationId;
       this.immunizationName = immunizationName;
       this.immunizationType = immunizationType;
       this.suggestedAge = suggestedAge;
       this.immunizationAgent = immunizationAgent;
       this.patientImmunizations = patientImmunizations;
    }
   
    public int getImmunizationId() {
        return this.immunizationId;
    }
    
    public void setImmunizationId(int immunizationId) {
        this.immunizationId = immunizationId;
    }
    public String getImmunizationName() {
        return this.immunizationName;
    }
    
    public void setImmunizationName(String immunizationName) {
        this.immunizationName = immunizationName;
    }
    public String getImmunizationType() {
        return this.immunizationType;
    }
    
    public void setImmunizationType(String immunizationType) {
        this.immunizationType = immunizationType;
    }
    public String getSuggestedAge() {
        return this.suggestedAge;
    }
    
    public void setSuggestedAge(String suggestedAge) {
        this.suggestedAge = suggestedAge;
    }
    public String getImmunizationAgent() {
        return this.immunizationAgent;
    }
    
    public void setImmunizationAgent(String immunizationAgent) {
        this.immunizationAgent = immunizationAgent;
    }
    public Set<PatientImmunization> getPatientImmunizations() {
        return this.patientImmunizations;
    }
    
    public void setPatientImmunizations(Set<PatientImmunization> patientImmunizations) {
        this.patientImmunizations = patientImmunizations;
    }




}


