package com.parsd.patientengine.pojo;
// Generated Apr 19, 2016 7:35:31 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * InsuranceLk generated by hbm2java
 */
@Entity
@Table(name="insurance_lk"
    ,catalog="patient"
)
public class InsuranceLk  implements java.io.Serializable {


     private String companyId;
     private String copmanyName;
     private Set<PatientInsuranceHistory> patientInsuranceHistories = new HashSet<PatientInsuranceHistory>(0);

    public InsuranceLk() {
    }

	
    public InsuranceLk(String companyId, String copmanyName) {
        this.companyId = companyId;
        this.copmanyName = copmanyName;
    }
    public InsuranceLk(String companyId, String copmanyName, Set<PatientInsuranceHistory> patientInsuranceHistories) {
       this.companyId = companyId;
       this.copmanyName = copmanyName;
       this.patientInsuranceHistories = patientInsuranceHistories;
    }
   
     @Id 

    
    @Column(name="company_id", unique=true, nullable=false, length=6)
    public String getCompanyId() {
        return this.companyId;
    }
    
    public void setCompanyId(String companyId) {
        this.companyId = companyId;
    }

    
    @Column(name="copmany_name", nullable=false, length=40)
    public String getCopmanyName() {
        return this.copmanyName;
    }
    
    public void setCopmanyName(String copmanyName) {
        this.copmanyName = copmanyName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="insuranceLk")
    public Set<PatientInsuranceHistory> getPatientInsuranceHistories() {
        return this.patientInsuranceHistories;
    }
    
    public void setPatientInsuranceHistories(Set<PatientInsuranceHistory> patientInsuranceHistories) {
        this.patientInsuranceHistories = patientInsuranceHistories;
    }




}


