package com.parsd.patientengine.pojo;
// Generated Apr 20, 2016 9:22:47 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * InsuranceLk generated by hbm2java
 */
public class InsuranceLk  implements java.io.Serializable {


     private String companyId;
     private String copmanyName;
     private Set<PatientInsuranceHistory> patientInsuranceHistories = new HashSet<PatientInsuranceHistory>(0);

    public InsuranceLk() {
    }

	
    public InsuranceLk(String companyId, String copmanyName) {
        this.companyId = companyId;
        this.copmanyName = copmanyName;
    }
    public InsuranceLk(String companyId, String copmanyName, Set<PatientInsuranceHistory> patientInsuranceHistories) {
       this.companyId = companyId;
       this.copmanyName = copmanyName;
       this.patientInsuranceHistories = patientInsuranceHistories;
    }
   
    public String getCompanyId() {
        return this.companyId;
    }
    
    public void setCompanyId(String companyId) {
        this.companyId = companyId;
    }
    public String getCopmanyName() {
        return this.copmanyName;
    }
    
    public void setCopmanyName(String copmanyName) {
        this.copmanyName = copmanyName;
    }
    public Set<PatientInsuranceHistory> getPatientInsuranceHistories() {
        return this.patientInsuranceHistories;
    }
    
    public void setPatientInsuranceHistories(Set<PatientInsuranceHistory> patientInsuranceHistories) {
        this.patientInsuranceHistories = patientInsuranceHistories;
    }




}


