package com.parsd.patientengine.pojo;
// Generated Apr 19, 2016 7:35:31 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 * LabTestImages generated by hbm2java
 */
@Entity
@Table(name="lab_test_images"
    ,catalog="patient"
)
public class LabTestImages  implements java.io.Serializable {


     private LabTestImagesId id;
     private LabTestHistory labTestHistory;
     private String testImage;

    public LabTestImages() {
    }

    public LabTestImages(LabTestHistory labTestHistory, String testImage) {
       this.labTestHistory = labTestHistory;
       this.testImage = testImage;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="patientUpi", column=@Column(name="patient_UPI", nullable=false, length=6) ), 
        @AttributeOverride(name="doctorId", column=@Column(name="doctor_id", nullable=false) ), 
        @AttributeOverride(name="eventDate", column=@Column(name="event_date", nullable=false, length=10) ), 
        @AttributeOverride(name="testId", column=@Column(name="test_id", nullable=false) ) } )
    public LabTestImagesId getId() {
        return this.id;
    }
    
    public void setId(LabTestImagesId id) {
        this.id = id;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public LabTestHistory getLabTestHistory() {
        return this.labTestHistory;
    }
    
    public void setLabTestHistory(LabTestHistory labTestHistory) {
        this.labTestHistory = labTestHistory;
    }

    
    @Column(name="test_image", nullable=false)
    public String getTestImage() {
        return this.testImage;
    }
    
    public void setTestImage(String testImage) {
        this.testImage = testImage;
    }




}


