package com.parsd.patientengine.pojo;
// Generated Apr 19, 2016 7:35:31 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * LabTestLk generated by hbm2java
 */
@Entity
@Table(name="lab_test_lk"
    ,catalog="patient"
)
public class LabTestLk  implements java.io.Serializable {


     private int testId;
     private String testType;
     private String testDescription;
     private int aboveOptimal;
     private int belowOptimal;
     private Set<LabTestHistory> labTestHistories = new HashSet<LabTestHistory>(0);

    public LabTestLk() {
    }

	
    public LabTestLk(int testId, String testType, String testDescription, int aboveOptimal, int belowOptimal) {
        this.testId = testId;
        this.testType = testType;
        this.testDescription = testDescription;
        this.aboveOptimal = aboveOptimal;
        this.belowOptimal = belowOptimal;
    }
    public LabTestLk(int testId, String testType, String testDescription, int aboveOptimal, int belowOptimal, Set<LabTestHistory> labTestHistories) {
       this.testId = testId;
       this.testType = testType;
       this.testDescription = testDescription;
       this.aboveOptimal = aboveOptimal;
       this.belowOptimal = belowOptimal;
       this.labTestHistories = labTestHistories;
    }
   
     @Id 

    
    @Column(name="test_id", unique=true, nullable=false)
    public int getTestId() {
        return this.testId;
    }
    
    public void setTestId(int testId) {
        this.testId = testId;
    }

    
    @Column(name="test_type", nullable=false, length=20)
    public String getTestType() {
        return this.testType;
    }
    
    public void setTestType(String testType) {
        this.testType = testType;
    }

    
    @Column(name="test_description", nullable=false)
    public String getTestDescription() {
        return this.testDescription;
    }
    
    public void setTestDescription(String testDescription) {
        this.testDescription = testDescription;
    }

    
    @Column(name="above_optimal", nullable=false)
    public int getAboveOptimal() {
        return this.aboveOptimal;
    }
    
    public void setAboveOptimal(int aboveOptimal) {
        this.aboveOptimal = aboveOptimal;
    }

    
    @Column(name="below_optimal", nullable=false)
    public int getBelowOptimal() {
        return this.belowOptimal;
    }
    
    public void setBelowOptimal(int belowOptimal) {
        this.belowOptimal = belowOptimal;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="labTestLk")
    public Set<LabTestHistory> getLabTestHistories() {
        return this.labTestHistories;
    }
    
    public void setLabTestHistories(Set<LabTestHistory> labTestHistories) {
        this.labTestHistories = labTestHistories;
    }




}


