package com.parsd.patientengine.pojo;
// Generated Apr 20, 2016 9:22:47 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * LabTestLk generated by hbm2java
 */
public class LabTestLk  implements java.io.Serializable {


     private int testId;
     private String testType;
     private String testDescription;
     private int aboveOptimal;
     private int belowOptimal;
     private Set<LabTestHistory> labTestHistories = new HashSet<LabTestHistory>(0);

    public LabTestLk() {
    }

	
    public LabTestLk(int testId, String testType, String testDescription, int aboveOptimal, int belowOptimal) {
        this.testId = testId;
        this.testType = testType;
        this.testDescription = testDescription;
        this.aboveOptimal = aboveOptimal;
        this.belowOptimal = belowOptimal;
    }
    public LabTestLk(int testId, String testType, String testDescription, int aboveOptimal, int belowOptimal, Set<LabTestHistory> labTestHistories) {
       this.testId = testId;
       this.testType = testType;
       this.testDescription = testDescription;
       this.aboveOptimal = aboveOptimal;
       this.belowOptimal = belowOptimal;
       this.labTestHistories = labTestHistories;
    }
   
    public int getTestId() {
        return this.testId;
    }
    
    public void setTestId(int testId) {
        this.testId = testId;
    }
    public String getTestType() {
        return this.testType;
    }
    
    public void setTestType(String testType) {
        this.testType = testType;
    }
    public String getTestDescription() {
        return this.testDescription;
    }
    
    public void setTestDescription(String testDescription) {
        this.testDescription = testDescription;
    }
    public int getAboveOptimal() {
        return this.aboveOptimal;
    }
    
    public void setAboveOptimal(int aboveOptimal) {
        this.aboveOptimal = aboveOptimal;
    }
    public int getBelowOptimal() {
        return this.belowOptimal;
    }
    
    public void setBelowOptimal(int belowOptimal) {
        this.belowOptimal = belowOptimal;
    }
    public Set<LabTestHistory> getLabTestHistories() {
        return this.labTestHistories;
    }
    
    public void setLabTestHistories(Set<LabTestHistory> labTestHistories) {
        this.labTestHistories = labTestHistories;
    }




}


