package com.parsd.patientengine.pojo;
// Generated Apr 19, 2016 7:35:31 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MedicationLk generated by hbm2java
 */
@Entity
@Table(name="medication_lk"
    ,catalog="patient"
)
public class MedicationLk  implements java.io.Serializable {


     private int drugNdc;
     private String drugName;
     private String drugForm;
     private int drugStrength;
     private Set<Prescription> prescriptions = new HashSet<Prescription>(0);

    public MedicationLk() {
    }

	
    public MedicationLk(int drugNdc, String drugName, String drugForm, int drugStrength) {
        this.drugNdc = drugNdc;
        this.drugName = drugName;
        this.drugForm = drugForm;
        this.drugStrength = drugStrength;
    }
    public MedicationLk(int drugNdc, String drugName, String drugForm, int drugStrength, Set<Prescription> prescriptions) {
       this.drugNdc = drugNdc;
       this.drugName = drugName;
       this.drugForm = drugForm;
       this.drugStrength = drugStrength;
       this.prescriptions = prescriptions;
    }
   
     @Id 

    
    @Column(name="drug_NDC", unique=true, nullable=false)
    public int getDrugNdc() {
        return this.drugNdc;
    }
    
    public void setDrugNdc(int drugNdc) {
        this.drugNdc = drugNdc;
    }

    
    @Column(name="drug_name", nullable=false, length=30)
    public String getDrugName() {
        return this.drugName;
    }
    
    public void setDrugName(String drugName) {
        this.drugName = drugName;
    }

    
    @Column(name="drug_form", nullable=false, length=20)
    public String getDrugForm() {
        return this.drugForm;
    }
    
    public void setDrugForm(String drugForm) {
        this.drugForm = drugForm;
    }

    
    @Column(name="drug_strength", nullable=false)
    public int getDrugStrength() {
        return this.drugStrength;
    }
    
    public void setDrugStrength(int drugStrength) {
        this.drugStrength = drugStrength;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="medicationLk")
    public Set<Prescription> getPrescriptions() {
        return this.prescriptions;
    }
    
    public void setPrescriptions(Set<Prescription> prescriptions) {
        this.prescriptions = prescriptions;
    }




}


