package com.parsd.patientengine.pojo;
// Generated Apr 20, 2016 9:22:47 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * MedicationLk generated by hbm2java
 */
public class MedicationLk  implements java.io.Serializable {


     private int drugNdc;
     private String drugName;
     private String drugForm;
     private int drugStrength;
     private Set<Prescription> prescriptions = new HashSet<Prescription>(0);

    public MedicationLk() {
    }

	
    public MedicationLk(int drugNdc, String drugName, String drugForm, int drugStrength) {
        this.drugNdc = drugNdc;
        this.drugName = drugName;
        this.drugForm = drugForm;
        this.drugStrength = drugStrength;
    }
    public MedicationLk(int drugNdc, String drugName, String drugForm, int drugStrength, Set<Prescription> prescriptions) {
       this.drugNdc = drugNdc;
       this.drugName = drugName;
       this.drugForm = drugForm;
       this.drugStrength = drugStrength;
       this.prescriptions = prescriptions;
    }
   
    public int getDrugNdc() {
        return this.drugNdc;
    }
    
    public void setDrugNdc(int drugNdc) {
        this.drugNdc = drugNdc;
    }
    public String getDrugName() {
        return this.drugName;
    }
    
    public void setDrugName(String drugName) {
        this.drugName = drugName;
    }
    public String getDrugForm() {
        return this.drugForm;
    }
    
    public void setDrugForm(String drugForm) {
        this.drugForm = drugForm;
    }
    public int getDrugStrength() {
        return this.drugStrength;
    }
    
    public void setDrugStrength(int drugStrength) {
        this.drugStrength = drugStrength;
    }
    public Set<Prescription> getPrescriptions() {
        return this.prescriptions;
    }
    
    public void setPrescriptions(Set<Prescription> prescriptions) {
        this.prescriptions = prescriptions;
    }




}


