package com.parsd.patientengine.pojo;
// Generated Apr 19, 2016 7:35:31 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PatientDiseaseSummary generated by hbm2java
 */
@Entity
@Table(name="patient_disease_summary"
    ,catalog="patient"
)
public class PatientDiseaseSummary  implements java.io.Serializable {


     private PatientDiseaseSummaryId id;
     private DiseaseLk diseaseLk;
     private Patient patient;
     private char diseaseStatus;
     private Date observationDate;
     private String symptoms;

    public PatientDiseaseSummary() {
    }

    public PatientDiseaseSummary(PatientDiseaseSummaryId id, DiseaseLk diseaseLk, Patient patient, char diseaseStatus, Date observationDate, String symptoms) {
       this.id = id;
       this.diseaseLk = diseaseLk;
       this.patient = patient;
       this.diseaseStatus = diseaseStatus;
       this.observationDate = observationDate;
       this.symptoms = symptoms;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="patientUpi", column=@Column(name="patient_UPI", nullable=false, length=6) ), 
        @AttributeOverride(name="diseaseIcd10", column=@Column(name="disease_ICD_10", nullable=false, length=7) ) } )
    public PatientDiseaseSummaryId getId() {
        return this.id;
    }
    
    public void setId(PatientDiseaseSummaryId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="disease_ICD_10", nullable=false, insertable=false, updatable=false)
    public DiseaseLk getDiseaseLk() {
        return this.diseaseLk;
    }
    
    public void setDiseaseLk(DiseaseLk diseaseLk) {
        this.diseaseLk = diseaseLk;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="patient_UPI", nullable=false, insertable=false, updatable=false)
    public Patient getPatient() {
        return this.patient;
    }
    
    public void setPatient(Patient patient) {
        this.patient = patient;
    }

    
    @Column(name="disease_status", nullable=false, length=1)
    public char getDiseaseStatus() {
        return this.diseaseStatus;
    }
    
    public void setDiseaseStatus(char diseaseStatus) {
        this.diseaseStatus = diseaseStatus;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="observation_date", nullable=false, length=19)
    public Date getObservationDate() {
        return this.observationDate;
    }
    
    public void setObservationDate(Date observationDate) {
        this.observationDate = observationDate;
    }

    
    @Column(name="symptoms", nullable=false, length=50)
    public String getSymptoms() {
        return this.symptoms;
    }
    
    public void setSymptoms(String symptoms) {
        this.symptoms = symptoms;
    }




}


