package com.parsd.patientengine.pojo;
// Generated Apr 20, 2016 9:22:47 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * PatientImmunization generated by hbm2java
 */
public class PatientImmunization  implements java.io.Serializable {


     private PatientImmunizationId id;
     private ImmunizationDetailsLk immunizationDetailsLk;
     private Patient patient;
     private String dosage;
     private String immunizationStatus;
     private Date dateTaken;

    public PatientImmunization() {
    }

    public PatientImmunization(PatientImmunizationId id, ImmunizationDetailsLk immunizationDetailsLk, Patient patient, String dosage, String immunizationStatus, Date dateTaken) {
       this.id = id;
       this.immunizationDetailsLk = immunizationDetailsLk;
       this.patient = patient;
       this.dosage = dosage;
       this.immunizationStatus = immunizationStatus;
       this.dateTaken = dateTaken;
    }
   
    public PatientImmunizationId getId() {
        return this.id;
    }
    
    public void setId(PatientImmunizationId id) {
        this.id = id;
    }
    public ImmunizationDetailsLk getImmunizationDetailsLk() {
        return this.immunizationDetailsLk;
    }
    
    public void setImmunizationDetailsLk(ImmunizationDetailsLk immunizationDetailsLk) {
        this.immunizationDetailsLk = immunizationDetailsLk;
    }
    public Patient getPatient() {
        return this.patient;
    }
    
    public void setPatient(Patient patient) {
        this.patient = patient;
    }
    public String getDosage() {
        return this.dosage;
    }
    
    public void setDosage(String dosage) {
        this.dosage = dosage;
    }
    public String getImmunizationStatus() {
        return this.immunizationStatus;
    }
    
    public void setImmunizationStatus(String immunizationStatus) {
        this.immunizationStatus = immunizationStatus;
    }
    public Date getDateTaken() {
        return this.dateTaken;
    }
    
    public void setDateTaken(Date dateTaken) {
        this.dateTaken = dateTaken;
    }




}


