package com.parsd.patientengine.pojo;
// Generated Apr 19, 2016 7:35:31 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PatientImmunization generated by hbm2java
 */
@Entity
@Table(name="patient_immunization"
    ,catalog="patient"
)
public class PatientImmunization  implements java.io.Serializable {


     private PatientImmunizationId id;
     private ImmunizationDetailsLk immunizationDetailsLk;
     private Patient patient;
     private String dosage;
     private String immunizationStatus;
     private Date dateTaken;

    public PatientImmunization() {
    }

    public PatientImmunization(PatientImmunizationId id, ImmunizationDetailsLk immunizationDetailsLk, Patient patient, String dosage, String immunizationStatus, Date dateTaken) {
       this.id = id;
       this.immunizationDetailsLk = immunizationDetailsLk;
       this.patient = patient;
       this.dosage = dosage;
       this.immunizationStatus = immunizationStatus;
       this.dateTaken = dateTaken;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="patientUpi", column=@Column(name="patient_UPI", nullable=false, length=6) ), 
        @AttributeOverride(name="immunizationId", column=@Column(name="immunization_id", nullable=false) ) } )
    public PatientImmunizationId getId() {
        return this.id;
    }
    
    public void setId(PatientImmunizationId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="immunization_id", nullable=false, insertable=false, updatable=false)
    public ImmunizationDetailsLk getImmunizationDetailsLk() {
        return this.immunizationDetailsLk;
    }
    
    public void setImmunizationDetailsLk(ImmunizationDetailsLk immunizationDetailsLk) {
        this.immunizationDetailsLk = immunizationDetailsLk;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="patient_UPI", nullable=false, insertable=false, updatable=false)
    public Patient getPatient() {
        return this.patient;
    }
    
    public void setPatient(Patient patient) {
        this.patient = patient;
    }

    
    @Column(name="dosage", nullable=false, length=10)
    public String getDosage() {
        return this.dosage;
    }
    
    public void setDosage(String dosage) {
        this.dosage = dosage;
    }

    
    @Column(name="immunization_status", nullable=false, length=10)
    public String getImmunizationStatus() {
        return this.immunizationStatus;
    }
    
    public void setImmunizationStatus(String immunizationStatus) {
        this.immunizationStatus = immunizationStatus;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_taken", nullable=false, length=10)
    public Date getDateTaken() {
        return this.dateTaken;
    }
    
    public void setDateTaken(Date dateTaken) {
        this.dateTaken = dateTaken;
    }




}


