package com.parsd.patientengine.pojo;
// Generated Apr 20, 2016 9:22:47 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * PatientInsuranceHistory generated by hbm2java
 */
public class PatientInsuranceHistory  implements java.io.Serializable {


     private PatientInsuranceHistoryId id;
     private InsuranceLk insuranceLk;
     private Patient patient;
     private String insuranceNumber;
     private Date effectiveDate;
     private Date effectiveTill;

    public PatientInsuranceHistory() {
    }

	
    public PatientInsuranceHistory(PatientInsuranceHistoryId id, InsuranceLk insuranceLk, Patient patient, String insuranceNumber, Date effectiveDate) {
        this.id = id;
        this.insuranceLk = insuranceLk;
        this.patient = patient;
        this.insuranceNumber = insuranceNumber;
        this.effectiveDate = effectiveDate;
    }
    public PatientInsuranceHistory(PatientInsuranceHistoryId id, InsuranceLk insuranceLk, Patient patient, String insuranceNumber, Date effectiveDate, Date effectiveTill) {
       this.id = id;
       this.insuranceLk = insuranceLk;
       this.patient = patient;
       this.insuranceNumber = insuranceNumber;
       this.effectiveDate = effectiveDate;
       this.effectiveTill = effectiveTill;
    }
   
    public PatientInsuranceHistoryId getId() {
        return this.id;
    }
    
    public void setId(PatientInsuranceHistoryId id) {
        this.id = id;
    }
    public InsuranceLk getInsuranceLk() {
        return this.insuranceLk;
    }
    
    public void setInsuranceLk(InsuranceLk insuranceLk) {
        this.insuranceLk = insuranceLk;
    }
    public Patient getPatient() {
        return this.patient;
    }
    
    public void setPatient(Patient patient) {
        this.patient = patient;
    }
    public String getInsuranceNumber() {
        return this.insuranceNumber;
    }
    
    public void setInsuranceNumber(String insuranceNumber) {
        this.insuranceNumber = insuranceNumber;
    }
    public Date getEffectiveDate() {
        return this.effectiveDate;
    }
    
    public void setEffectiveDate(Date effectiveDate) {
        this.effectiveDate = effectiveDate;
    }
    public Date getEffectiveTill() {
        return this.effectiveTill;
    }
    
    public void setEffectiveTill(Date effectiveTill) {
        this.effectiveTill = effectiveTill;
    }




}


