package com.parsd.patientengine.pojo;
// Generated Apr 19, 2016 7:35:31 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PatientAllergy generated by hbm2java
 */
@Entity
@Table(name="patient_allergy"
    ,catalog="patient"
)
public class PatientAllergy  implements java.io.Serializable {


     private PatientAllergyId id;
     private AllergyLk allergyLk;
     private Patient patient;
     private String allergyStatus;
     private char allergySeverity;
     private String allergyReaction;
     private Date allergyIdentificationDate;

    public PatientAllergy() {
    }

    public PatientAllergy(PatientAllergyId id, AllergyLk allergyLk, Patient patient, String allergyStatus, char allergySeverity, String allergyReaction, Date allergyIdentificationDate) {
       this.id = id;
       this.allergyLk = allergyLk;
       this.patient = patient;
       this.allergyStatus = allergyStatus;
       this.allergySeverity = allergySeverity;
       this.allergyReaction = allergyReaction;
       this.allergyIdentificationDate = allergyIdentificationDate;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="patientUpi", column=@Column(name="patient_UPI", nullable=false, length=6) ), 
        @AttributeOverride(name="allergyId", column=@Column(name="allergy_id", nullable=false) ) } )
    public PatientAllergyId getId() {
        return this.id;
    }
    
    public void setId(PatientAllergyId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="allergy_id", nullable=false, insertable=false, updatable=false)
    public AllergyLk getAllergyLk() {
        return this.allergyLk;
    }
    
    public void setAllergyLk(AllergyLk allergyLk) {
        this.allergyLk = allergyLk;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="patient_UPI", nullable=false, insertable=false, updatable=false)
    public Patient getPatient() {
        return this.patient;
    }
    
    public void setPatient(Patient patient) {
        this.patient = patient;
    }

    
    @Column(name="allergy_status", nullable=false, length=10)
    public String getAllergyStatus() {
        return this.allergyStatus;
    }
    
    public void setAllergyStatus(String allergyStatus) {
        this.allergyStatus = allergyStatus;
    }

    
    @Column(name="allergy_severity", nullable=false, length=1)
    public char getAllergySeverity() {
        return this.allergySeverity;
    }
    
    public void setAllergySeverity(char allergySeverity) {
        this.allergySeverity = allergySeverity;
    }

    
    @Column(name="allergy_reaction", nullable=false, length=50)
    public String getAllergyReaction() {
        return this.allergyReaction;
    }
    
    public void setAllergyReaction(String allergyReaction) {
        this.allergyReaction = allergyReaction;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="allergy_identification_date", nullable=false, length=10)
    public Date getAllergyIdentificationDate() {
        return this.allergyIdentificationDate;
    }
    
    public void setAllergyIdentificationDate(Date allergyIdentificationDate) {
        this.allergyIdentificationDate = allergyIdentificationDate;
    }




}


