package com.parsd.patientengine.pojo;
// Generated Apr 19, 2016 7:35:31 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PatientDisability generated by hbm2java
 */
@Entity
@Table(name="patient_disability"
    ,catalog="patient"
)
public class PatientDisability  implements java.io.Serializable {


     private PatientDisabilityId id;
     private DisabilityLk disabilityLk;
     private Patient patient;
     private BigDecimal disabilityPercentage;

    public PatientDisability() {
    }

    public PatientDisability(PatientDisabilityId id, DisabilityLk disabilityLk, Patient patient, BigDecimal disabilityPercentage) {
       this.id = id;
       this.disabilityLk = disabilityLk;
       this.patient = patient;
       this.disabilityPercentage = disabilityPercentage;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="patientUpi", column=@Column(name="patient_UPI", nullable=false, length=6) ), 
        @AttributeOverride(name="disabilityId", column=@Column(name="disability_id", nullable=false) ) } )
    public PatientDisabilityId getId() {
        return this.id;
    }
    
    public void setId(PatientDisabilityId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="disability_id", nullable=false, insertable=false, updatable=false)
    public DisabilityLk getDisabilityLk() {
        return this.disabilityLk;
    }
    
    public void setDisabilityLk(DisabilityLk disabilityLk) {
        this.disabilityLk = disabilityLk;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="patient_UPI", nullable=false, insertable=false, updatable=false)
    public Patient getPatient() {
        return this.patient;
    }
    
    public void setPatient(Patient patient) {
        this.patient = patient;
    }

    
    @Column(name="disability_percentage", nullable=false, precision=4)
    public BigDecimal getDisabilityPercentage() {
        return this.disabilityPercentage;
    }
    
    public void setDisabilityPercentage(BigDecimal disabilityPercentage) {
        this.disabilityPercentage = disabilityPercentage;
    }




}


