package com.parsd.patientengine.pojo;
// Generated Apr 19, 2016 7:35:31 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PatientAllergyId generated by hbm2java
 */
@Embeddable
public class PatientAllergyId  implements java.io.Serializable {


     private String patientUpi;
     private int allergyId;

    public PatientAllergyId() {
    }

    public PatientAllergyId(String patientUpi, int allergyId) {
       this.patientUpi = patientUpi;
       this.allergyId = allergyId;
    }
   


    @Column(name="patient_UPI", nullable=false, length=6)
    public String getPatientUpi() {
        return this.patientUpi;
    }
    
    public void setPatientUpi(String patientUpi) {
        this.patientUpi = patientUpi;
    }


    @Column(name="allergy_id", nullable=false)
    public int getAllergyId() {
        return this.allergyId;
    }
    
    public void setAllergyId(int allergyId) {
        this.allergyId = allergyId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PatientAllergyId) ) return false;
		 PatientAllergyId castOther = ( PatientAllergyId ) other; 
         
		 return ( (this.getPatientUpi()==castOther.getPatientUpi()) || ( this.getPatientUpi()!=null && castOther.getPatientUpi()!=null && this.getPatientUpi().equals(castOther.getPatientUpi()) ) )
 && (this.getAllergyId()==castOther.getAllergyId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPatientUpi() == null ? 0 : this.getPatientUpi().hashCode() );
         result = 37 * result + this.getAllergyId();
         return result;
   }   


}


