package com.parsd.patientengine.pojo;
// Generated Apr 20, 2016 9:22:47 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * PatientAllergy generated by hbm2java
 */
public class PatientAllergy  implements java.io.Serializable {


     private PatientAllergyId id;
     private AllergyLk allergyLk;
     private Patient patient;
     private String allergyStatus;
     private char allergySeverity;
     private String allergyReaction;
     private Date allergyIdentificationDate;

    public PatientAllergy() {
    }

    public PatientAllergy(PatientAllergyId id, AllergyLk allergyLk, Patient patient, String allergyStatus, char allergySeverity, String allergyReaction, Date allergyIdentificationDate) {
       this.id = id;
       this.allergyLk = allergyLk;
       this.patient = patient;
       this.allergyStatus = allergyStatus;
       this.allergySeverity = allergySeverity;
       this.allergyReaction = allergyReaction;
       this.allergyIdentificationDate = allergyIdentificationDate;
    }
   
    public PatientAllergyId getId() {
        return this.id;
    }
    
    public void setId(PatientAllergyId id) {
        this.id = id;
    }
    public AllergyLk getAllergyLk() {
        return this.allergyLk;
    }
    
    public void setAllergyLk(AllergyLk allergyLk) {
        this.allergyLk = allergyLk;
    }
    public Patient getPatient() {
        return this.patient;
    }
    
    public void setPatient(Patient patient) {
        this.patient = patient;
    }
    public String getAllergyStatus() {
        return this.allergyStatus;
    }
    
    public void setAllergyStatus(String allergyStatus) {
        this.allergyStatus = allergyStatus;
    }
    public char getAllergySeverity() {
        return this.allergySeverity;
    }
    
    public void setAllergySeverity(char allergySeverity) {
        this.allergySeverity = allergySeverity;
    }
    public String getAllergyReaction() {
        return this.allergyReaction;
    }
    
    public void setAllergyReaction(String allergyReaction) {
        this.allergyReaction = allergyReaction;
    }
    public Date getAllergyIdentificationDate() {
        return this.allergyIdentificationDate;
    }
    
    public void setAllergyIdentificationDate(Date allergyIdentificationDate) {
        this.allergyIdentificationDate = allergyIdentificationDate;
    }




}


