package com.parsd.patientengine.pojo;
// Generated Apr 20, 2016 9:22:47 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * PatientDisability generated by hbm2java
 */
public class PatientDisability  implements java.io.Serializable {


     private PatientDisabilityId id;
     private DisabilityLk disabilityLk;
     private Patient patient;
     private BigDecimal disabilityPercentage;

    public PatientDisability() {
    }

    public PatientDisability(PatientDisabilityId id, DisabilityLk disabilityLk, Patient patient, BigDecimal disabilityPercentage) {
       this.id = id;
       this.disabilityLk = disabilityLk;
       this.patient = patient;
       this.disabilityPercentage = disabilityPercentage;
    }
   
    public PatientDisabilityId getId() {
        return this.id;
    }
    
    public void setId(PatientDisabilityId id) {
        this.id = id;
    }
    public DisabilityLk getDisabilityLk() {
        return this.disabilityLk;
    }
    
    public void setDisabilityLk(DisabilityLk disabilityLk) {
        this.disabilityLk = disabilityLk;
    }
    public Patient getPatient() {
        return this.patient;
    }
    
    public void setPatient(Patient patient) {
        this.patient = patient;
    }
    public BigDecimal getDisabilityPercentage() {
        return this.disabilityPercentage;
    }
    
    public void setDisabilityPercentage(BigDecimal disabilityPercentage) {
        this.disabilityPercentage = disabilityPercentage;
    }




}


