package com.parsd.patientengine.pojo;
// Generated Apr 19, 2016 7:35:31 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PatientInsuranceHistoryId generated by hbm2java
 */
@Embeddable
public class PatientInsuranceHistoryId  implements java.io.Serializable {


     private String patientUpi;
     private String companyId;

    public PatientInsuranceHistoryId() {
    }

    public PatientInsuranceHistoryId(String patientUpi, String companyId) {
       this.patientUpi = patientUpi;
       this.companyId = companyId;
    }
   


    @Column(name="patient_UPI", nullable=false, length=6)
    public String getPatientUpi() {
        return this.patientUpi;
    }
    
    public void setPatientUpi(String patientUpi) {
        this.patientUpi = patientUpi;
    }


    @Column(name="company_id", nullable=false, length=6)
    public String getCompanyId() {
        return this.companyId;
    }
    
    public void setCompanyId(String companyId) {
        this.companyId = companyId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PatientInsuranceHistoryId) ) return false;
		 PatientInsuranceHistoryId castOther = ( PatientInsuranceHistoryId ) other; 
         
		 return ( (this.getPatientUpi()==castOther.getPatientUpi()) || ( this.getPatientUpi()!=null && castOther.getPatientUpi()!=null && this.getPatientUpi().equals(castOther.getPatientUpi()) ) )
 && ( (this.getCompanyId()==castOther.getCompanyId()) || ( this.getCompanyId()!=null && castOther.getCompanyId()!=null && this.getCompanyId().equals(castOther.getCompanyId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPatientUpi() == null ? 0 : this.getPatientUpi().hashCode() );
         result = 37 * result + ( getCompanyId() == null ? 0 : this.getCompanyId().hashCode() );
         return result;
   }   


}


