package com.parsd.patientengine.pojo;
// Generated Apr 19, 2016 7:35:31 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * PatientInsuranceHistory generated by hbm2java
 */
@Entity
@Table(name="patient_insurance_history"
    ,catalog="patient"
    , uniqueConstraints = @UniqueConstraint(columnNames="insurance_number") 
)
public class PatientInsuranceHistory  implements java.io.Serializable {


     private PatientInsuranceHistoryId id;
     private InsuranceLk insuranceLk;
     private Patient patient;
     private String insuranceNumber;
     private Date effectiveDate;
     private Date effectiveTill;

    public PatientInsuranceHistory() {
    }

	
    public PatientInsuranceHistory(PatientInsuranceHistoryId id, InsuranceLk insuranceLk, Patient patient, String insuranceNumber, Date effectiveDate) {
        this.id = id;
        this.insuranceLk = insuranceLk;
        this.patient = patient;
        this.insuranceNumber = insuranceNumber;
        this.effectiveDate = effectiveDate;
    }
    public PatientInsuranceHistory(PatientInsuranceHistoryId id, InsuranceLk insuranceLk, Patient patient, String insuranceNumber, Date effectiveDate, Date effectiveTill) {
       this.id = id;
       this.insuranceLk = insuranceLk;
       this.patient = patient;
       this.insuranceNumber = insuranceNumber;
       this.effectiveDate = effectiveDate;
       this.effectiveTill = effectiveTill;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="patientUpi", column=@Column(name="patient_UPI", nullable=false, length=6) ), 
        @AttributeOverride(name="companyId", column=@Column(name="company_id", nullable=false, length=6) ) } )
    public PatientInsuranceHistoryId getId() {
        return this.id;
    }
    
    public void setId(PatientInsuranceHistoryId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="company_id", nullable=false, insertable=false, updatable=false)
    public InsuranceLk getInsuranceLk() {
        return this.insuranceLk;
    }
    
    public void setInsuranceLk(InsuranceLk insuranceLk) {
        this.insuranceLk = insuranceLk;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="patient_UPI", nullable=false, insertable=false, updatable=false)
    public Patient getPatient() {
        return this.patient;
    }
    
    public void setPatient(Patient patient) {
        this.patient = patient;
    }

    
    @Column(name="insurance_number", unique=true, nullable=false, length=6)
    public String getInsuranceNumber() {
        return this.insuranceNumber;
    }
    
    public void setInsuranceNumber(String insuranceNumber) {
        this.insuranceNumber = insuranceNumber;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="effective_date", nullable=false, length=10)
    public Date getEffectiveDate() {
        return this.effectiveDate;
    }
    
    public void setEffectiveDate(Date effectiveDate) {
        this.effectiveDate = effectiveDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="effective_till", length=10)
    public Date getEffectiveTill() {
        return this.effectiveTill;
    }
    
    public void setEffectiveTill(Date effectiveTill) {
        this.effectiveTill = effectiveTill;
    }




}


