package com.parsd.patientengine.pojo;
// Generated Apr 20, 2016 9:22:47 PM by Hibernate Tools 4.3.1



/**
 * PatientDisabilityId generated by hbm2java
 */
public class PatientDisabilityId  implements java.io.Serializable {


     private String patientUpi;
     private int disabilityId;

    public PatientDisabilityId() {
    }

    public PatientDisabilityId(String patientUpi, int disabilityId) {
       this.patientUpi = patientUpi;
       this.disabilityId = disabilityId;
    }
   
    public String getPatientUpi() {
        return this.patientUpi;
    }
    
    public void setPatientUpi(String patientUpi) {
        this.patientUpi = patientUpi;
    }
    public int getDisabilityId() {
        return this.disabilityId;
    }
    
    public void setDisabilityId(int disabilityId) {
        this.disabilityId = disabilityId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PatientDisabilityId) ) return false;
		 PatientDisabilityId castOther = ( PatientDisabilityId ) other; 
         
		 return ( (this.getPatientUpi()==castOther.getPatientUpi()) || ( this.getPatientUpi()!=null && castOther.getPatientUpi()!=null && this.getPatientUpi().equals(castOther.getPatientUpi()) ) )
 && (this.getDisabilityId()==castOther.getDisabilityId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPatientUpi() == null ? 0 : this.getPatientUpi().hashCode() );
         result = 37 * result + this.getDisabilityId();
         return result;
   }   


}


