package com.parsd.patientengine.pojo;
// Generated Apr 19, 2016 7:35:31 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PrescriptionId generated by hbm2java
 */
@Embeddable
public class PrescriptionId  implements java.io.Serializable {


     private int prescriptionId;
     private String patientUpi;
     private int doctorId;
     private int drugNdc;
     private Date eventDate;

    public PrescriptionId() {
    }

    public PrescriptionId(int prescriptionId, String patientUpi, int doctorId, int drugNdc, Date eventDate) {
       this.prescriptionId = prescriptionId;
       this.patientUpi = patientUpi;
       this.doctorId = doctorId;
       this.drugNdc = drugNdc;
       this.eventDate = eventDate;
    }
   


    @Column(name="prescription_id", nullable=false)
    public int getPrescriptionId() {
        return this.prescriptionId;
    }
    
    public void setPrescriptionId(int prescriptionId) {
        this.prescriptionId = prescriptionId;
    }


    @Column(name="patient_UPI", nullable=false, length=6)
    public String getPatientUpi() {
        return this.patientUpi;
    }
    
    public void setPatientUpi(String patientUpi) {
        this.patientUpi = patientUpi;
    }


    @Column(name="doctor_id", nullable=false)
    public int getDoctorId() {
        return this.doctorId;
    }
    
    public void setDoctorId(int doctorId) {
        this.doctorId = doctorId;
    }


    @Column(name="drug_NDC", nullable=false)
    public int getDrugNdc() {
        return this.drugNdc;
    }
    
    public void setDrugNdc(int drugNdc) {
        this.drugNdc = drugNdc;
    }


    @Column(name="event_date", nullable=false, length=10)
    public Date getEventDate() {
        return this.eventDate;
    }
    
    public void setEventDate(Date eventDate) {
        this.eventDate = eventDate;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PrescriptionId) ) return false;
		 PrescriptionId castOther = ( PrescriptionId ) other; 
         
		 return (this.getPrescriptionId()==castOther.getPrescriptionId())
 && ( (this.getPatientUpi()==castOther.getPatientUpi()) || ( this.getPatientUpi()!=null && castOther.getPatientUpi()!=null && this.getPatientUpi().equals(castOther.getPatientUpi()) ) )
 && (this.getDoctorId()==castOther.getDoctorId())
 && (this.getDrugNdc()==castOther.getDrugNdc())
 && ( (this.getEventDate()==castOther.getEventDate()) || ( this.getEventDate()!=null && castOther.getEventDate()!=null && this.getEventDate().equals(castOther.getEventDate()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPrescriptionId();
         result = 37 * result + ( getPatientUpi() == null ? 0 : this.getPatientUpi().hashCode() );
         result = 37 * result + this.getDoctorId();
         result = 37 * result + this.getDrugNdc();
         result = 37 * result + ( getEventDate() == null ? 0 : this.getEventDate().hashCode() );
         return result;
   }   


}


