package com.parsd.patientengine.pojo;
// Generated Apr 19, 2016 7:35:31 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Prescription generated by hbm2java
 */
@Entity
@Table(name="prescription"
    ,catalog="patient"
)
public class Prescription  implements java.io.Serializable {


     private PrescriptionId id;
     private MedicationLk medicationLk;
     private PatientEvent patientEvent;
     private String drugDosage;
     private String doctorNotes;

    public Prescription() {
    }

	
    public Prescription(PrescriptionId id, MedicationLk medicationLk, PatientEvent patientEvent, String drugDosage) {
        this.id = id;
        this.medicationLk = medicationLk;
        this.patientEvent = patientEvent;
        this.drugDosage = drugDosage;
    }
    public Prescription(PrescriptionId id, MedicationLk medicationLk, PatientEvent patientEvent, String drugDosage, String doctorNotes) {
       this.id = id;
       this.medicationLk = medicationLk;
       this.patientEvent = patientEvent;
       this.drugDosage = drugDosage;
       this.doctorNotes = doctorNotes;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="prescriptionId", column=@Column(name="prescription_id", nullable=false) ), 
        @AttributeOverride(name="patientUpi", column=@Column(name="patient_UPI", nullable=false, length=6) ), 
        @AttributeOverride(name="doctorId", column=@Column(name="doctor_id", nullable=false) ), 
        @AttributeOverride(name="drugNdc", column=@Column(name="drug_NDC", nullable=false) ), 
        @AttributeOverride(name="eventDate", column=@Column(name="event_date", nullable=false, length=10) ) } )
    public PrescriptionId getId() {
        return this.id;
    }
    
    public void setId(PrescriptionId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="drug_NDC", nullable=false, insertable=false, updatable=false)
    public MedicationLk getMedicationLk() {
        return this.medicationLk;
    }
    
    public void setMedicationLk(MedicationLk medicationLk) {
        this.medicationLk = medicationLk;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="patient_UPI", referencedColumnName="patient_UPI", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="doctor_id", referencedColumnName="doctor_id", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="event_date", referencedColumnName="event_date", nullable=false, insertable=false, updatable=false) } )
    public PatientEvent getPatientEvent() {
        return this.patientEvent;
    }
    
    public void setPatientEvent(PatientEvent patientEvent) {
        this.patientEvent = patientEvent;
    }

    
    @Column(name="drug_dosage", nullable=false, length=20)
    public String getDrugDosage() {
        return this.drugDosage;
    }
    
    public void setDrugDosage(String drugDosage) {
        this.drugDosage = drugDosage;
    }

    
    @Column(name="doctor_notes")
    public String getDoctorNotes() {
        return this.doctorNotes;
    }
    
    public void setDoctorNotes(String doctorNotes) {
        this.doctorNotes = doctorNotes;
    }




}


