package com.parsd.patientengine.pojo;
// Generated Apr 19, 2016 7:35:31 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ProcedureLk generated by hbm2java
 */
@Entity
@Table(name="procedure_lk"
    ,catalog="patient"
)
public class ProcedureLk  implements java.io.Serializable {


     private int procedureId;
     private String procedureDesc;
     private Set<Treatment> treatments = new HashSet<Treatment>(0);
     private Set<PatientSurgeryDetails> patientSurgeryDetailses = new HashSet<PatientSurgeryDetails>(0);

    public ProcedureLk() {
    }

	
    public ProcedureLk(int procedureId, String procedureDesc) {
        this.procedureId = procedureId;
        this.procedureDesc = procedureDesc;
    }
    public ProcedureLk(int procedureId, String procedureDesc, Set<Treatment> treatments, Set<PatientSurgeryDetails> patientSurgeryDetailses) {
       this.procedureId = procedureId;
       this.procedureDesc = procedureDesc;
       this.treatments = treatments;
       this.patientSurgeryDetailses = patientSurgeryDetailses;
    }
   
     @Id 

    
    @Column(name="procedure_id", unique=true, nullable=false)
    public int getProcedureId() {
        return this.procedureId;
    }
    
    public void setProcedureId(int procedureId) {
        this.procedureId = procedureId;
    }

    
    @Column(name="procedure_desc", nullable=false)
    public String getProcedureDesc() {
        return this.procedureDesc;
    }
    
    public void setProcedureDesc(String procedureDesc) {
        this.procedureDesc = procedureDesc;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="procedureLk")
    public Set<Treatment> getTreatments() {
        return this.treatments;
    }
    
    public void setTreatments(Set<Treatment> treatments) {
        this.treatments = treatments;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="procedureLk")
    public Set<PatientSurgeryDetails> getPatientSurgeryDetailses() {
        return this.patientSurgeryDetailses;
    }
    
    public void setPatientSurgeryDetailses(Set<PatientSurgeryDetails> patientSurgeryDetailses) {
        this.patientSurgeryDetailses = patientSurgeryDetailses;
    }




}


