package com.parsd.patientengine.pojo;
// Generated Apr 19, 2016 7:35:31 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Surgery generated by hbm2java
 */
@Entity
@Table(name="surgery"
    ,catalog="patient"
)
public class Surgery  implements java.io.Serializable {


     private int surgeryId;
     private String surgeryType;

    public Surgery() {
    }

    public Surgery(int surgeryId, String surgeryType) {
       this.surgeryId = surgeryId;
       this.surgeryType = surgeryType;
    }
   
     @Id 

    
    @Column(name="surgery_id", unique=true, nullable=false)
    public int getSurgeryId() {
        return this.surgeryId;
    }
    
    public void setSurgeryId(int surgeryId) {
        this.surgeryId = surgeryId;
    }

    
    @Column(name="surgery_type", nullable=false, length=30)
    public String getSurgeryType() {
        return this.surgeryType;
    }
    
    public void setSurgeryType(String surgeryType) {
        this.surgeryType = surgeryType;
    }




}


