package com.parsd.patientengine.pojo;
// Generated Apr 20, 2016 9:22:47 PM by Hibernate Tools 4.3.1



/**
 * Surgery generated by hbm2java
 */
public class Surgery  implements java.io.Serializable {


     private int surgeryId;
     private String surgeryType;

    public Surgery() {
    }

    public Surgery(int surgeryId, String surgeryType) {
       this.surgeryId = surgeryId;
       this.surgeryType = surgeryType;
    }
   
    public int getSurgeryId() {
        return this.surgeryId;
    }
    
    public void setSurgeryId(int surgeryId) {
        this.surgeryId = surgeryId;
    }
    public String getSurgeryType() {
        return this.surgeryType;
    }
    
    public void setSurgeryType(String surgeryType) {
        this.surgeryType = surgeryType;
    }




}


