package com.parsd.patientengine.pojo;
// Generated Apr 19, 2016 7:35:31 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 * Treatment generated by hbm2java
 */
@Entity
@Table(name="treatment"
    ,catalog="patient"
)
public class Treatment  implements java.io.Serializable {


     private TreatmentId id;
     private PatientEvent patientEvent;
     private ProcedureLk procedureLk;
     private String treatmentDesc;

    public Treatment() {
    }

	
    public Treatment(PatientEvent patientEvent) {
        this.patientEvent = patientEvent;
    }
    public Treatment(PatientEvent patientEvent, ProcedureLk procedureLk, String treatmentDesc) {
       this.patientEvent = patientEvent;
       this.procedureLk = procedureLk;
       this.treatmentDesc = treatmentDesc;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="patientUpi", column=@Column(name="patient_UPI", nullable=false, length=6) ), 
        @AttributeOverride(name="doctorId", column=@Column(name="doctor_id", nullable=false) ), 
        @AttributeOverride(name="eventDate", column=@Column(name="event_date", nullable=false, length=10) ) } )
    public TreatmentId getId() {
        return this.id;
    }
    
    public void setId(TreatmentId id) {
        this.id = id;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public PatientEvent getPatientEvent() {
        return this.patientEvent;
    }
    
    public void setPatientEvent(PatientEvent patientEvent) {
        this.patientEvent = patientEvent;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="procedure_id")
    public ProcedureLk getProcedureLk() {
        return this.procedureLk;
    }
    
    public void setProcedureLk(ProcedureLk procedureLk) {
        this.procedureLk = procedureLk;
    }

    
    @Column(name="treatment_desc")
    public String getTreatmentDesc() {
        return this.treatmentDesc;
    }
    
    public void setTreatmentDesc(String treatmentDesc) {
        this.treatmentDesc = treatmentDesc;
    }




}


