package com.parsd.patientengine.pojo;
// Generated Apr 20, 2016 9:22:47 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * VitalSigns generated by hbm2java
 */
public class VitalSigns  implements java.io.Serializable {


     private VitalSignsId id;
     private PatientEvent patientEvent;
     private BigDecimal bodyTemperaure;
     private short pulseRate;
     private short respirationRate;
     private short bloodPressureDiastolic;
     private short bloodPressureSystolic;
     private BigDecimal weight;

    public VitalSigns() {
    }

    public VitalSigns(PatientEvent patientEvent, BigDecimal bodyTemperaure, short pulseRate, short respirationRate, short bloodPressureDiastolic, short bloodPressureSystolic, BigDecimal weight) {
       this.patientEvent = patientEvent;
       this.bodyTemperaure = bodyTemperaure;
       this.pulseRate = pulseRate;
       this.respirationRate = respirationRate;
       this.bloodPressureDiastolic = bloodPressureDiastolic;
       this.bloodPressureSystolic = bloodPressureSystolic;
       this.weight = weight;
    }
   
    public VitalSignsId getId() {
        return this.id;
    }
    
    public void setId(VitalSignsId id) {
        this.id = id;
    }
    public PatientEvent getPatientEvent() {
        return this.patientEvent;
    }
    
    public void setPatientEvent(PatientEvent patientEvent) {
        this.patientEvent = patientEvent;
    }
    public BigDecimal getBodyTemperaure() {
        return this.bodyTemperaure;
    }
    
    public void setBodyTemperaure(BigDecimal bodyTemperaure) {
        this.bodyTemperaure = bodyTemperaure;
    }
    public short getPulseRate() {
        return this.pulseRate;
    }
    
    public void setPulseRate(short pulseRate) {
        this.pulseRate = pulseRate;
    }
    public short getRespirationRate() {
        return this.respirationRate;
    }
    
    public void setRespirationRate(short respirationRate) {
        this.respirationRate = respirationRate;
    }
    public short getBloodPressureDiastolic() {
        return this.bloodPressureDiastolic;
    }
    
    public void setBloodPressureDiastolic(short bloodPressureDiastolic) {
        this.bloodPressureDiastolic = bloodPressureDiastolic;
    }
    public short getBloodPressureSystolic() {
        return this.bloodPressureSystolic;
    }
    
    public void setBloodPressureSystolic(short bloodPressureSystolic) {
        this.bloodPressureSystolic = bloodPressureSystolic;
    }
    public BigDecimal getWeight() {
        return this.weight;
    }
    
    public void setWeight(BigDecimal weight) {
        this.weight = weight;
    }




}


