package com.parsd.patientengine.pojo;
// Generated Apr 19, 2016 7:35:31 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 * VitalSigns generated by hbm2java
 */
@Entity
@Table(name="vital_signs"
    ,catalog="patient"
)
public class VitalSigns  implements java.io.Serializable {


     private VitalSignsId id;
     private PatientEvent patientEvent;
     private BigDecimal bodyTemperaure;
     private short pulseRate;
     private short respirationRate;
     private short bloodPressureDiastolic;
     private short bloodPressureSystolic;
     private BigDecimal weight;

    public VitalSigns() {
    }

    public VitalSigns(PatientEvent patientEvent, BigDecimal bodyTemperaure, short pulseRate, short respirationRate, short bloodPressureDiastolic, short bloodPressureSystolic, BigDecimal weight) {
       this.patientEvent = patientEvent;
       this.bodyTemperaure = bodyTemperaure;
       this.pulseRate = pulseRate;
       this.respirationRate = respirationRate;
       this.bloodPressureDiastolic = bloodPressureDiastolic;
       this.bloodPressureSystolic = bloodPressureSystolic;
       this.weight = weight;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="patientUpi", column=@Column(name="patient_UPI", nullable=false, length=6) ), 
        @AttributeOverride(name="doctorId", column=@Column(name="doctor_id", nullable=false) ), 
        @AttributeOverride(name="eventDate", column=@Column(name="event_date", nullable=false, length=10) ) } )
    public VitalSignsId getId() {
        return this.id;
    }
    
    public void setId(VitalSignsId id) {
        this.id = id;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public PatientEvent getPatientEvent() {
        return this.patientEvent;
    }
    
    public void setPatientEvent(PatientEvent patientEvent) {
        this.patientEvent = patientEvent;
    }

    
    @Column(name="body_temperaure", nullable=false, precision=5)
    public BigDecimal getBodyTemperaure() {
        return this.bodyTemperaure;
    }
    
    public void setBodyTemperaure(BigDecimal bodyTemperaure) {
        this.bodyTemperaure = bodyTemperaure;
    }

    
    @Column(name="pulse_rate", nullable=false, precision=3, scale=0)
    public short getPulseRate() {
        return this.pulseRate;
    }
    
    public void setPulseRate(short pulseRate) {
        this.pulseRate = pulseRate;
    }

    
    @Column(name="respiration_rate", nullable=false, precision=3, scale=0)
    public short getRespirationRate() {
        return this.respirationRate;
    }
    
    public void setRespirationRate(short respirationRate) {
        this.respirationRate = respirationRate;
    }

    
    @Column(name="blood_pressure_diastolic", nullable=false, precision=3, scale=0)
    public short getBloodPressureDiastolic() {
        return this.bloodPressureDiastolic;
    }
    
    public void setBloodPressureDiastolic(short bloodPressureDiastolic) {
        this.bloodPressureDiastolic = bloodPressureDiastolic;
    }

    
    @Column(name="blood_pressure_systolic", nullable=false, precision=3, scale=0)
    public short getBloodPressureSystolic() {
        return this.bloodPressureSystolic;
    }
    
    public void setBloodPressureSystolic(short bloodPressureSystolic) {
        this.bloodPressureSystolic = bloodPressureSystolic;
    }

    
    @Column(name="weight", nullable=false, precision=5)
    public BigDecimal getWeight() {
        return this.weight;
    }
    
    public void setWeight(BigDecimal weight) {
        this.weight = weight;
    }




}


