package com.parsd.patientengine.pojo;
// Generated Apr 20, 2016 9:22:47 PM by Hibernate Tools 4.3.1



/**
 * WardDetails generated by hbm2java
 */
public class WardDetails  implements java.io.Serializable {


     private String wardId;
     private String wardType;

    public WardDetails() {
    }

    public WardDetails(String wardId, String wardType) {
       this.wardId = wardId;
       this.wardType = wardType;
    }
   
    public String getWardId() {
        return this.wardId;
    }
    
    public void setWardId(String wardId) {
        this.wardId = wardId;
    }
    public String getWardType() {
        return this.wardType;
    }
    
    public void setWardType(String wardType) {
        this.wardType = wardType;
    }




}


